### ISSUE TITLE
Wobble.Audio.AudioEngineException on linux

### ISSUE THREAD

**Issue by nobbele** [Quaver/Quaver#1160]
I keep getting this error when trying to open the game

    RUNTIME - ERROR: Wobble.Audio.AudioEngineException: BASS has failed to initialize (error code: 3, name: "Driver")! Are your platform-specific dlls present?

**Desktop:**
 - OS: Linux, Pop!_OS

**Comment by nobbele** [comment]
Interestingly osu lazer works fine(both games uses Bass(ManagedBass)). What it does differently is that it specifies a device index it seems https://github.com/ppy/osu-framework/blob/master/osu.Framework/Audio/AudioManager.cs line 203

**Comment by nobbele** [comment]
Actually I solved it after moving libbass.so to /lib. The game should move it or tell you to move it so I guess this shouldn't be closed

**Comment by OtterGauze** [comment]
I seem to be having a similar issue with this library, on the same OS no-less. I'll refrain from using the method mentioned earlier, as that seems to be discouraged.

```
[5:36:53] - RUNTIME - DEBUG: OS: Linux 5.3.0-7625-generic #27~1576774560~19.10~f432cd8-Ubuntu SMP Thu Dec 19 20:35:37 UTC 
[5:36:53] - NETWORK - DEBUG: OS: Linux 5.3.0-7625-generic #27~1576774560~19.10~f432cd8-Ubuntu SMP Thu Dec 19 20:35:37 UTC 
[5:36:53] - RUNTIME - IMPORTANT: Started IPC server on port: 43596
[5:36:53] - RUNTIME - ERROR: System.DllNotFoundException: Unable to load shared library 'bass' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libbass: cannot open shared object file: No such file or directory
   at ManagedBass.Bass.GetConfig(Configuration Option)
   at Quaver.Shared.Config.ConfigManager.ReadConfigFile() in /home/matt/storage/main/Quaver/Quaver.Shared/Config/ConfigManager.cs:line 657
   at Quaver.Shared.Config.ConfigManager.Initialize() in /home/matt/storage/main/Quaver/Quaver.Shared/Config/ConfigManager.cs:line 619
   at Quaver.Program.Run() in /home/matt/storage/main/Quaver/Quaver/Program.cs:line 103
   at Quaver.Program.Main(String[] args) in /home/matt/storage/main/Quaver/Quaver/Program.cs:line 63

Unhandled Exception: System.DllNotFoundException: Unable to load shared library 'bass' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libbass: cannot open shared object file: No such file or directory
   at ManagedBass.Bass.GetConfig(Configuration Option)
   at Quaver.Shared.Config.ConfigManager.ReadConfigFile() in /home/matt/storage/main/Quaver/Quaver.Shared/Config/ConfigManager.cs:line 657
   at Quaver.Shared.Config.ConfigManager.Initialize() in /home/matt/storage/main/Quaver/Quaver.Shared/Config/ConfigManager.cs:line 619
   at Quaver.Program.Run() in /home/matt/storage/main/Quaver/Quaver/Program.cs:line 103
   at Quaver.Program.Main(String[] args) in /home/matt/storage/main/Quaver/Quaver/Program.cs:line 63
```

libbass is definitely present within the repo, and it was cloned directly.

**Comment by YaLTeR** [comment]
So yeah, I'm not sure this is actionable. The issue here is likely with the audio system—if somebody encounters this it's advised to check that pulseaudio is installed, that pulseaudio-alsa integration is installed and that the audio works correctly in general.
