### ISSUE TITLE
Quaver fails to import map (Entry is trying to write a file outside of the destination directory.)

### ISSUE THREAD

**Issue by IceDynamix** [Quaver/Quaver#1200]
**Describe the bug**
Quaver fails to import this [map](https://osu.ppy.sh/beatmapsets/1058330#mania/2216601).

**To Reproduce**
1. Download the mapset from https://osu.ppy.sh/beatmapsets/1058330#mania/2216601
2. Import it into Quaver

**Expected behavior**
The map to be imported normally

**Notes**
Map has notes before the first timing point (shouldn't be an issue?) and some SV.

[runtime.log](https://github.com/Quaver/Quaver/files/3786390/runtime.log)

**Comment by IceDynamix** [comment]
Exporting from the osu.db imported mapset, then reimporting works fine though

**Comment by IceDynamix** [comment]
I've had a lot of issues with this map already. I wanted to update it, so I reimported the osu.db exported file and pasted the file contents into the uploaded diff, then updated. Now: 
- The [uploaded mapset](https://quavergame.com/mapsets/607) only contains the mp3
- I can't reimport the osu.db map ([runtime.log](https://github.com/Quaver/Quaver/files/3789995/runtime.log))
- Mapsets that I've deleted still show up in song select (without bg and music)
![explorer_2019-10-30_17-06-18](https://user-images.githubusercontent.com/22303902/67876306-f8f3a180-fb37-11e9-82cb-5d434e28c697.png)

**Comment by KaidenFrizu** [comment]
> 1. Download the mapset from https://osu.ppy.sh/beatmapsets/1058330#mania/2216601

I tried importing this mapset but it produces no error message and the mapset is nowhere to be seen in the game. I checked `temp` and there's the folder of the song but the content is just the mapset still in .osz format.

---

Also, this map also produces the same error but this time, it explicitly tells that an error was made: https://osu.ppy.sh/beatmapsets/634241

When I checked `temp`, the files are just the keysounds used in the mapset and it seems unfinished.

![image](https://user-images.githubusercontent.com/39328974/91713416-4f989480-ebbc-11ea-8936-307f96a42aa7.png)

In `runtime.log`
```
[6:38:34] - RUNTIME - IMPORTANT: Scheduled screen change to: 'Importing'. w/ 0 ms delay
[6:38:34] - RUNTIME - IMPORTANT: Changed to Screen 'Importing'
[6:38:34] - RUNTIME - ERROR: SharpCompress.Common.ExtractionException: Entry is trying to write a file outside of the destination directory.
   at SharpCompress.Common.ExtractionMethods.WriteEntryToDirectory(IEntry entry, String destinationDirectory, ExtractionOptions options, Action`2 write)
   at Quaver.Shared.Converters.Osu.Osu.ConvertOsz(String file, String extractDirectory)
[6:38:34] - RUNTIME - ERROR: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Program Files (x86)\Steam\steamapps\common\Quaver\Songs\634241 Nanahira - Petals - 371'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, Boolean isNormalized, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at Quaver.Shared.Database.Maps.MapsetImporter.InsertAndUpdateSelectedMap(String extractDirectory)
   at Quaver.Shared.Database.Maps.MapsetImporter.ImportMapsetsInQueue()
```
