### ISSUE TITLE
[redesign] Notifications allegedly crashes the game on screen change (ubuntu)

### ISSUE THREAD

**Issue by Adrriii** [Quaver/Quaver#1234]
```
[1:37:52] - RUNTIME - ERROR: System.NullReferenceException: Object reference not set to an instance of an object.
   at Quaver.Shared.Graphics.Overlays.Hub.Notifications.NotificationScrollContainer.Update(GameTime gameTime)
   at Wobble.Graphics.Drawable.Update(GameTime gameTime)

```

Got this error while loading a map several times (frenquently). Also got it once while returning from a screen.

**Comment by Swan** [comment]
Fixed in #1235
