### ISSUE TITLE
Spurious crash while playing a map

### ISSUE THREAD

**Issue by YaLTeR** [Quaver/Quaver#1333]
I was playing the Lv.16 difficulty of [this map](https://github.com/Quaver/Quaver/files/3907370/P.E.-.HAL.-Eternal.Girl-.-.8932.zip) and in the very end the game crashed. Surprisingly, the score saved, which makes me doubt my memory on whether it was this map that I was playing.
```
[8:06:31] - RUNTIME - ERROR: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at Quaver.Shared.Screens.Gameplay.GameplayScreen.HandleSoundEffects() in /home/yalter/source/cs/Quaver/Quaver.Shared/Screens/Gameplay/GameplayScreen.cs:line 1286
   at Quaver.Shared.Screens.Gameplay.GameplayScreen.Update(GameTime gameTime) in /home/yalter/source/cs/Quaver/Quaver.Shared/Screens/Gameplay/GameplayScreen.cs:line 432
   at Wobble.WobbleGame.Update(GameTime gameTime) in /home/yalter/source/cs/Quaver/Wobble/Wobble/WobbleGame.cs:line 171
   at Quaver.Shared.QuaverGame.Update(GameTime gameTime) in /home/yalter/source/cs/Quaver/Quaver.Shared/QuaverGame.cs:line 310
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in /home/yalter/source/cs/Quaver/Wobble/MonoGame/MonoGame.Framework/Game.cs:line 657
   at Microsoft.Xna.Framework.Game.Tick() in /home/yalter/source/cs/Quaver/Wobble/MonoGame/MonoGame.Framework/Game.cs:line 507
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in /home/yalter/source/cs/Quaver/Wobble/MonoGame/MonoGame.Framework/Platform/SDL/SDLGamePlatform.cs:line 134
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in /home/yalter/source/cs/Quaver/Wobble/MonoGame/MonoGame.Framework/Game.cs:line 401
   at Quaver.Program.Run() in /home/yalter/source/cs/Quaver/Quaver/Program.cs:line 120
   at Quaver.Program.Main(String[] args) in /home/yalter/source/cs/Quaver/Quaver/Program.cs:line 63
```

**Comment by YaLTeR** [comment]
Had the same crash happen with another BMS convert and the score had also saved.

**Comment by YaLTeR** [comment]
I have just had keysounds from one map load into the other map that I selected next in the song select. I highly suspect this issue to be caused by a variation of that.
