### ISSUE TITLE
Game crash while spectating

### ISSUE THREAD

**Issue by robby250** [Quaver/Quaver#1359]
```
[3:59:54] - RUNTIME - ERROR: System.NullReferenceException: Object reference not set to an instance of an object.
   at Quaver.Shared.Screens.Gameplay.Rulesets.Keys.HitObjects.HitObjectManagerKeys.get_ScrollSpeed()
   at Quaver.Shared.Screens.Gameplay.Rulesets.Keys.HitObjects.GameplayHitObjectKeys.GetSpritePosition(Int64 offset)
   at Quaver.Shared.Screens.Gameplay.Rulesets.Keys.HitObjects.GameplayHitObjectKeys.UpdateSpritePositions(Int64 offset)
   at Quaver.Shared.Screens.Gameplay.Rulesets.Keys.HitObjects.GameplayHitObjectKeys.InitializeObject(HitObjectManagerKeys manager, HitObjectInfo info)
   at Quaver.Shared.Screens.Gameplay.Rulesets.Keys.HitObjects.HitObjectManagerKeys.CreatePoolObject(HitObjectInfo info)
   at Quaver.Shared.Screens.Gameplay.Rulesets.Keys.HitObjects.HitObjectManagerKeys.InitializeObjectPool()
   at Quaver.Shared.Screens.Gameplay.GameplayScreen.HandleSpectatorSkipping()
   at Quaver.Shared.Screens.Gameplay.GameplayScreen.Update(GameTime gameTime)
   at Wobble.WobbleGame.Update(GameTime gameTime)
   at Quaver.Shared.QuaverGame.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Quaver.Program.Run()
   at Quaver.Program.Main(String[] args)

```

**Comment by AiAe** [comment]
Starting to spectate someone and going to watch replay from someone else leads to crashing with that error.
