### ISSUE TITLE
Can't load osu map when in subfolders in osu's songs folder

### ISSUE THREAD

**Issue by ElectroYan** [Quaver/Quaver#1420]
**Describe the bug**
Kinda similar to #258. 
If you move osu maps to subfolders (for example to structure them), Quaver can't load them in-game anymore. They're shown in the song select menu but neither the image nor the song/map is loaded when starting it (For error message see screenshot).

**To Reproduce**
1. Move a (osu) map to a subdirectory in the songs folder.
2. Reload the maps in osu so it gets updated in the db
3. Import the db to Quaver
4. Select the song you moved to a subdirectory

**Expected behavior**
Should find the song despite being in subfolders.

**Screenshots**
https://i.imgur.com/GTfqeo3.png

**Additional information**
It does show a calculated difficulty, so I assume it was able to find the file at some point. I've only recently moved songs to subfolders and those songs were loaded in Quaver before, so maybe it kept this information but didn't update the new path. When trying this with a completely new map there was no calculated difficulty in Quaver.

**Comment by ElectroYan** [comment]
I've did some research and it is able to load maps when they're in subdirectories. Just when you move them and they're already in quaver's database, paths won't be updated. I consider closing this issue since the main aspect of it is wrong.

**Comment by KeepSOBP** [comment]
I have this error too. not fixed
```log
[4:58:04] - RUNTIME - IMPORTANT: Scheduled screen change to: 'Select'. w/ 0 ms delay
[4:58:04] - RUNTIME - IMPORTANT: Changed to Screen 'Select'
[4:58:04] - RUNTIME - ERROR: System.ArgumentException: The .qua file is invalid. It does not have HitObjects, TimingPoints, its Mode is invalid or some hit objects are invalid.
   at Quaver.API.Maps.Parsers.OsuBeatmap.ToQua()
   at Quaver.Shared.Database.Maps.Map.LoadQua(Boolean checkValidity)
   at Quaver.Shared.Screens.Selection.UI.Preview.SelectMapPreviewContainer.HandleLoadGameplayScreen(Map map, CancellationToken token)
[4:58:04] - RUNTIME - IMPORTANT: Fetched 0 Local scores for map: Kaneko Chiharu - Lachryma<Re:Queen'M> [BASIC] | Has PB: False
[4:58:11] - RUNTIME - ERROR: System.ArgumentException: The .qua file is invalid. It does not have HitObjects, TimingPoints, its Mode is invalid or some hit objects are invalid.
   at Quaver.API.Maps.Parsers.OsuBeatmap.ToQua()
   at Quaver.Shared.Database.Maps.Map.LoadQua(Boolean checkValidity)
   at Quaver.Shared.Screens.Selection.UI.Preview.SelectMapPreviewContainer.HandleLoadGameplayScreen(Map map, CancellationToken token)
[4:58:11] - RUNTIME - IMPORTANT: Fetched 0 Local scores for map: Greatvictory - Greatvictory Song Covers Compilation [Camellia - K.Y.A.F.A.] | Has PB: False
[4:58:11] - RUNTIME - IMPORTANT: Scheduled screen change to: 'Loading'. w/ 0 ms delay
[4:58:12] - RUNTIME - IMPORTANT: Changed to Screen 'Loading'
[4:58:12] - RUNTIME - ERROR: System.ArgumentException: The .qua file is invalid. It does not have HitObjects, TimingPoints, its Mode is invalid or some hit objects are invalid.
   at Quaver.API.Maps.Parsers.OsuBeatmap.ToQua()
   at Quaver.Shared.Database.Maps.Map.LoadQua(Boolean checkValidity)
   at Quaver.Shared.Screens.Loading.MapLoadingScreen.ParseAndLoadMap()
   at Quaver.Shared.Screens.Loading.MapLoadingScreen.<OnFirstUpdate>b__17_0()
[4:58:12] - RUNTIME - IMPORTANT: Scheduled screen change to: 'Select'. w/ 0 ms delay
[4:58:12] - RUNTIME - IMPORTANT: Changed to Screen 'Select'
[4:58:12] - RUNTIME - ERROR: System.ArgumentException: The .qua file is invalid. It does not have HitObjects, TimingPoints, its Mode is invalid or some hit objects are invalid.
   at Quaver.API.Maps.Parsers.OsuBeatmap.ToQua()
   at Quaver.Shared.Database.Maps.Map.LoadQua(Boolean checkValidity)
   at Quaver.Shared.Screens.Selection.UI.Preview.SelectMapPreviewContainer.HandleLoadGameplayScreen(Map map, CancellationToken token)
[4:58:12] - RUNTIME - IMPORTANT: Fetched 0 Local scores for map: Greatvictory - Greatvictory Song Covers Compilation [Camellia - K.Y.A.F.A.] | Has PB: False
```
