### ISSUE TITLE
Downloading a lot of maps at once leads to crash for notifications

### ISSUE THREAD

**Issue by AiAe** [Quaver/Quaver#1518]
```[8:28:50] - RUNTIME - ERROR: System.NullReferenceException: Object reference not set to an instance of an object.
   at Quaver.Shared.Graphics.Notifications.NotificationManager.FlushNotificationQueue()
   at Quaver.Shared.Graphics.Notifications.NotificationManager.Update(GameTime gameTime)
   at Quaver.Shared.QuaverGame.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Quaver.Program.Run()
   at Quaver.Program.Main(String[] args)```

**Comment by Swan** [comment]
Fixed in #2934
