### ISSUE TITLE
Downloading maps failed to import errors

### ISSUE THREAD

**Issue by AiAe** [Quaver/Quaver#1519]
[runtime.log](https://github.com/Quaver/Quaver/files/4155274/runtime.log) full log

```
[8:40:51] - RUNTIME - ERROR: System.OverflowException: Value was either too large or too small for a Single.
   at System.Number.ParseSingle(ReadOnlySpan`1 value, NumberStyles options, NumberFormatInfo numfmt)
   at Quaver.Shared.Screens.Downloading.UI.Filter.Items.DownloadFilterItemDifficultyTextbox.Update(GameTime gameTime)
   at Wobble.Graphics.Drawable.Update(GameTime gameTime)
```

and a lot of maps failed to import with error 

```
[8:43:35] - RUNTIME - ERROR: System.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\SteamLibrary\steamapps\common\Quaver\Songs\612 - 242'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at Quaver.Shared.Database.Maps.MapsetImporter.InsertAndUpdateSelectedMap(String extractDirectory)
   at Quaver.Shared.Database.Maps.MapsetImporter.ImportMapsetsInQueue()
```

```
[8:43:54] - RUNTIME - ERROR: SQLite.SQLiteException: Constraint
   at SQLite.PreparedSqlLiteInsertCommand.ExecuteNonQuery(Object[] source)
   at SQLite.SQLiteConnection.Insert(Object obj, String extra, Type objType)
   at Quaver.Shared.Database.Maps.MapDatabaseCache.InsertMap(Map map, String file)
```

**Comment by AiAe** [comment]
```[10:28:46] - NETWORK - IMPORTANT: Finished downloading mapset: 548. Cancelled: False | Error: System.Net.WebException: An exception occurred during a WebClient request. ---> System.IO.IOException: The process cannot access the file 'D:\SteamLibrary\steamapps\common\Quaver\Data\Downloads\548.qp' because it is being used by another process.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at System.Net.WebClient.DownloadFileAsync(Uri address, String fileName, Object userToken)
   --- End of inner exception stack trace ---
[10:28:46] - NETWORK - IMPORTANT: Downloading mapset 572...
[10:28:47] - NETWORK - ERROR: Wobble.Audio.AudioEngineException: Cannot call AfterLoad if stream isn't loaded.
   at Wobble.Audio.Tracks.AudioTrack.AfterLoad()
   at Quaver.Shared.Screens.Downloading.DownloadingScreen.<>c__DisplayClass139_0.<LoadAudioPreview>b__0()
[10:28:47] - NETWORK - ERROR: Wobble.Audio.AudioEngineException: Cannot call AfterLoad if stream isn't loaded.
   at Wobble.Audio.Tracks.AudioTrack.AfterLoad()
   at Quaver.Shared.Screens.Downloading.DownloadingScreen.<>c__DisplayClass139_0.<LoadAudioPreview>b__0()```

**Comment by AiAe** [comment]
Still getting this issue with importing with drag and drop on https://quavergame.com/mapset/map/14367 
Will attach file just in case the mapset change
[1439.zip](https://github.com/Quaver/Quaver/files/4913518/1439.zip)

```
[6:42:08] - RUNTIME - IMPORTANT: Changed to Screen 'Importing'
[6:42:09] - RUNTIME - ERROR: SQLite.SQLiteException: Constraint
   at SQLite.PreparedSqlLiteInsertCommand.ExecuteNonQuery(Object[] source)
   at SQLite.SQLiteConnection.Insert(Object obj, String extra, Type objType)
   at SQLite.SQLiteConnection.Insert(Object obj)
   at Quaver.Shared.Database.Maps.MapDatabaseCache.InsertMap(Map map, String file)
[6:42:09] - RUNTIME - IMPORTANT: Successfully imported C:\Users\AiAe\Downloads\1439 (1).qp
```
