### ISSUE TITLE
Maps with no timing points/note data crash when loading into the editor

### ISSUE THREAD

**Issue by Kangaroux** [Quaver/Quaver#1620]
**Describe the bug**
I dragged an mp3 to create a new song, filled out the metadata, and went back to the title screen (which prompted me to save and I said yes).

The song appeared in the song list as it should but attempting to open it in the editor gives a black screen and this in runtime.log

```
[11:12:19] - RUNTIME - ERROR: System.ArgumentException: The .qua file is invalid. It does not have HitObjects, TimingPoints, its Mode is invalid or some hit objects are invalid.
   at Quaver.API.Maps.Qua.AfterLoad(Qua qua, Boolean checkValidity)
   at Quaver.API.Maps.Qua.Parse(String path, Boolean checkValidity)
   at Quaver.Shared.Database.Maps.Map.LoadQua(Boolean checkValidity)
   at Quaver.Shared.Screens.Selection.SelectionScreen.<>c.<ExitToEditor>b__62_0()
   at Quaver.Shared.Screens.QuaverScreenManager.<>c__DisplayClass24_0.<ScheduleScreenChange>b__0()
   at Quaver.Shared.Scheduling.ThreadScheduler.<>c__DisplayClass1_0.<Run>b__0()
```

**To Reproduce**
1. Drag an mp3 to create a new mapset
2. Quit out of the editor before adding anything
3. Try editing the map (should go to a black screen, you can press escape to go back)

**Desktop (please complete the following information):**
 - OS: Windows 10 19041
 - Version 2.12.2020

**Comment by Kangaroux** [comment]
Also if someone could tell me how to unbrick my game that would be great lol

**Comment by Kangaroux** [comment]
Update: this appears to be related to/caused by #1660
