### ISSUE TITLE
Getting stuck on connection to mp game after qua error

### ISSUE THREAD

**Issue by AiAe** [Quaver/Quaver#1646]
Reproducing:
You need to have broken qua file ( i assume i got mine from older issue because I downloaded too many mapsets at once and few failed to import)
Went to create game and i got stuck on Joining game loading screen and got runtime error 
```[9:55:57] - RUNTIME - ERROR: System.ArgumentException: The .qua file is invalid. It does not have HitObjects, TimingPoints, its Mode is invalid or some hit objects are invalid.
   at Quaver.API.Maps.Parsers.OsuBeatmap.ToQua()
   at Quaver.Shared.Database.Maps.Map.LoadQua(Boolean checkValidity)
   at Quaver.Shared.Database.Maps.Map.GetAlternativeMd5()
   at Quaver.Shared.Screens.MultiplayerLobby.UI.Dialogs.Create.CreateGameDialog.<CreateGame>b__29_0()
   at Quaver.Shared.Scheduling.ThreadScheduler.<>c__DisplayClass1_0.<Run>b__0()
```
Song was probably `IMPORTANT: Fetched 0 Global scores for map: daisan - -+ [pw's 7K Hyper] | Has PB: False` not 100% sure about this because 2nd testing did not cause this to happen again

Thats also how some people manage to get -1 id on live multiplayer rooms that are on `https://quavergame.com/multiplayer/game/-1`

**Comment by Kangaroux** [comment]
https://github.com/Quaver/Quaver/issues/1620
