### ISSUE TITLE
Game crash mid-gameplay

### ISSUE THREAD

**Issue by robby250** [Quaver/Quaver#1777]
[runtime.log](https://github.com/Quaver/Quaver/files/4373885/runtime.log)

```
[9:59:45] - RUNTIME - ERROR: ManagedBass.BassException: Error: Handle
   at ManagedBass.Bass.ChannelGetInfo(Int32 Handle)
   at Wobble.Audio.Samples.AudioSampleChannel..ctor(AudioSample sample, Boolean isPitched, Single rate)
   at Quaver.Shared.Audio.CustomAudioSampleCache.Play(Int32 index, Int32 volume)
   at Quaver.Shared.Screens.Gameplay.Rulesets.HitObjects.HitObjectManager.PlayObjectKeySounds(HitObjectInfo hitObject)
   at Quaver.Shared.Screens.Gameplay.Rulesets.Input.KeysInputManager.HandleKeyPress(HitObjectManagerKeys manager, GameplayHitObjectKeys gameplayHitObject)
   at Quaver.Shared.Screens.Gameplay.Rulesets.Input.KeysInputManager.HandleInput(Double dt)
   at Quaver.Shared.Screens.Gameplay.Rulesets.GameplayRuleset.HandleInput(GameTime gameTime)
   at Quaver.Shared.Screens.Gameplay.GameplayScreen.HandleInput(GameTime gameTime)
   at Quaver.Shared.Screens.Gameplay.GameplayScreen.Update(GameTime gameTime)
   at Wobble.WobbleGame.Update(GameTime gameTime)
   at Quaver.Shared.QuaverGame.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Quaver.Program.Run()
   at Quaver.Program.Main(String[] args)
```

There are more errors in the log prior to this.

**Comment by robby250** [comment]
think it's a duplicate of https://github.com/Quaver/Quaver/issues/1017 actually
