### ISSUE TITLE
Map uploading error

### ISSUE THREAD

**Issue by Fretzi** [Quaver/Quaver#1977]
[9:44:02] - NETWORK - DEBUG: OS: Microsoft Windows 10.0.18362 
[9:44:06] - NETWORK - DEBUG: Requested Steam user information for user: 76561198049297993 - False
[9:44:06] - NETWORK - DEBUG: Requesting Steam Avatar for user: 76561198049297993...
[9:44:07] - NETWORK - DEBUG: Loaded Steam Avatar for user: 76561198049297993
[9:44:07] - NETWORK - IMPORTANT: Attempting to log into the Quaver server...
[9:44:19] - NETWORK - DEBUG: Requested Steam user information for user: 0 - False
[9:44:19] - NETWORK - DEBUG: Requesting Steam Avatar for user: 0...
[9:44:19] - NETWORK - DEBUG: Loaded Steam Avatar for user: 0
[9:44:29] - NETWORK - IMPORTANT: Beginning to upload mapset...
[9:44:29] - NETWORK - IMPORTANT: Successfully saved the current map
[9:45:33] - NETWORK - ERROR: Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Path '', line 0, position 0.
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at Quaver.Server.Client.OnlineClient.UploadMapset(String file)
   at Quaver.Shared.Screens.Edit.Dialogs.EditorUploadingMapsetDialog.<>c__DisplayClass3_0.<.ctor>b__0()

Tried to update one of my older maps (https://quavergame.com/mapsets/849), but only get this error. Done on v5.10.2020

**Comment by Fretzi** [comment]
After a PC restart, the map seems to be broken with a very awkward error
[runtime.log](https://github.com/Quaver/Quaver/files/4624446/runtime.log)
