### ISSUE TITLE
Hang on dragging an mp3 into "New Song" in the editor

### ISSUE THREAD

**Issue by YaLTeR** [Quaver/Quaver#2029]
```
[1:21:34] - RUNTIME - ERROR: System.NullReferenceException: Object reference not set to an instance of an object.
   at Quaver.Shared.Screens.Selection.UI.Preview.SelectMapPreviewContainer.OnMapChanged(Object sender, BindableValueChangedEventArgs`1 e) in /home/yalter/source/cs/Quaver/Quaver.Shared/Screens/Selection/UI/Preview/SelectMapPreviewContainer.cs:line 309
   at Wobble.Bindables.Bindable`1.set_Value(T value) in /home/yalter/source/cs/Quaver/Wobble/Wobble/Bindables/Bindable.cs:line 40
   at Quaver.Shared.Screens.Edit.EditScreen.<>c__DisplayClass152_0.<CreateNewMapset>b__0() in /home/yalter/source/cs/Quaver/Quaver.Shared/Screens/Edit/EditScreen.cs:line 1230
   at Quaver.Shared.Screens.QuaverScreenManager.<>c__DisplayClass24_0.<ScheduleScreenChange>b__0() in /home/yalter/source/cs/Quaver/Quaver.Shared/Screens/QuaverScreenManager.cs:line 205
   at Quaver.Shared.Scheduling.ThreadScheduler.<>c__DisplayClass1_0.<Run>b__0() in /home/yalter/source/cs/Quaver/Quaver.Shared/Scheduling/ThreadScheduler.cs:line 38
[1:21:39] - RUNTIME - IMPORTANT: Notification Missed: Error | Error occurred while running background thread. Check runtime.log!
```
and black screen hang. Happens every time.

**Comment by YaLTeR** [comment]
Also on creating a new difficulty even though it worked previously... Did I break something?
```
[1:24:24] - RUNTIME - ERROR: System.NullReferenceException: Object reference not set to an instance of an object.
   at Quaver.Shared.Screens.Selection.UI.Preview.SelectMapPreviewContainer.OnMapChanged(Object sender, BindableValueChangedEventArgs`1 e) in /home/yalter/source/cs/Quaver/Quaver.Shared/Screens/Selection/UI/Preview/SelectMapPreviewContainer.cs:line 309
   at Wobble.Bindables.Bindable`1.set_Value(T value) in /home/yalter/source/cs/Quaver/Wobble/Wobble/Bindables/Bindable.cs:line 40
   at Quaver.Shared.Screens.Edit.EditScreen.<>c__DisplayClass153_0.<CreateNewDifficulty>b__0() in /home/yalter/source/cs/Quaver/Quaver.Shared/Screens/Edit/EditScreen.cs:line 1285
[1:24:30] - RUNTIME - IMPORTANT: Notification Missed: Error | There was an issue while creating a new difficulty.
```
