### ISSUE TITLE
I can't submit scores

### ISSUE THREAD

**Issue by Tokakitake** [Quaver/Quaver#2323]
Almost on every score i get same errors and so much scores not submitted
- RUNTIME - ERROR: System.NullReferenceException: Object reference not set to an instance of an object.
   at Quaver.Shared.Screens.Results.ResultsScreen.OnScoreSubmitted(Object sender, ScoreSubmissionEventArgs e)
   at Quaver.Server.Client.OnlineClient.Submit(OnlineScore score)
   at Quaver.Shared.Screens.Results.ResultsScreen.SubmitOnlineScore(GameplayScreen screen, Replay replay)
   at Quaver.Shared.Screens.Results.ResultsScreen.<>cDisplayClass74_0.<SubmitScore>b0()
   at Quaver.Shared.Scheduling.ThreadScheduler.<>cDisplayClass1_0.<Run>b0()
![20200710184958_1](https://user-images.githubusercontent.com/65546504/87251773-d95a9a00-c476-11ea-9d02-e22e7addedb0.jpg)

**Comment by Swan** [comment]
Can you submit your entire log file along with the songs you are trying to play?

**Comment by Tokakitake** [comment]
Twice for ~50 min, not so much today
[network.log](https://github.com/Quaver/Quaver/files/4912979/network.log)
[runtime.log](https://github.com/Quaver/Quaver/files/4912980/runtime.log)
