### ISSUE TITLE
Game Crash in Download screen

### ISSUE THREAD

**Issue by Adrriii** [Quaver/Quaver#2345]
The game crashed when downloading a bunch of maps

[5:58:00] - RUNTIME - IMPORTANT: Changed to Screen 'Download'
[5:59:55] - RUNTIME - ERROR: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at Quaver.Shared.Graphics.Containers.PoolableScrollContainer`1.AddObject(Int32 index, Boolean updateContent)
   at Quaver.Shared.Graphics.Containers.PoolableScrollContainer`1.AddObjectToBottom(T obj, Boolean scrollTo, Boolean usePoolCount)
   at Quaver.Shared.Graphics.Overlays.Hub.Downloads.Scrolling.DownloadScrollContainer.OnDownloadAdded(Object sender, MapsetDownloadAddedEventArgs e)
   at Quaver.Shared.Screens.Download.MapsetDownloadManager.Download(Int32 id, String artist, String title)
   at Quaver.Shared.Screens.Downloading.DownloadingScreen.HandleKeyPressEnter()
   at Quaver.Shared.Screens.Downloading.DownloadingScreen.Update(GameTime gameTime)
   at Wobble.WobbleGame.Update(GameTime gameTime)
   at Quaver.Shared.QuaverGame.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Microsoft.Xna.Framework.Game.Run()
   at Quaver.Program.Run()
   at Quaver.Program.Main(String[] args)

**Comment by N1ckn1ght** [comment]
Happened just now.

```
[9:32:11] - RUNTIME - DEBUG: Updated map: 52fc5451ecbc7982ed3215a7a1a25855 (#720) in the cache
[9:32:12] - RUNTIME - IMPORTANT: Scheduled Screen Change
[9:32:12] - RUNTIME - IMPORTANT: Screen `Download` has been loaded proceeding to switch.
[9:32:12] - RUNTIME - IMPORTANT: Screen has been switched to type: `Download`
[9:32:56] - RUNTIME - ERROR: System.NullReferenceException: Object reference not set to an instance of an object.
   at (Object )
   at HmcaqKQyVs3Vnb7nB9bj.Myb5v5YTuOf(Object , HmcaqKQyVs3Vnb7nB9bj )
   at Quaver.Shared.Screens.Downloading.UI.Mapsets.DownloadableMapsetContainer.<>c__DisplayClass29_0.Y6UfMb7I0HR(DownloadableMapset x)
   at System.Collections.Generic.List`1.FindIndex(Int32 startIndex, Int32 count, Predicate`1 match)
   at System.Collections.Generic.List`1.FindIndex(Predicate`1 match)
   at Quaver.Shared.Screens.Downloading.UI.Mapsets.DownloadableMapsetContainer.<>c__DisplayClass29_0.nhFfMJDsZLP(Object o, BindableValueChangedEventArgs`1 args)
   at Quaver.Shared.Screens.Download.MapsetDownload.<>c__DisplayClass24_0.H7ufkLo4JLF(Object o, AsyncCompletedEventArgs e)
   at Quaver.Server.Client.OnlineClient.<>c__DisplayClass366_0.pcWRhetPWl4(Object o, AsyncCompletedEventArgs e)
   at System.Net.WebClient.OnDownloadFileCompleted(AsyncCompletedEventArgs e)
   at System.Net.WebClient.<StartAsyncOperation>b__78_4(Object arg)
   at System.Threading.QueueUserWorkItemCallback`1.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()

```
