### ISSUE TITLE
Stuck at System.ArgumentException: Empty path name is not legal.

### ISSUE THREAD

**Issue by marcostudios** [Quaver/Quaver#254]
I imported [this map](https://quavergame.com/mapsets/7) it got stuck at importing the map then i closed the game and reopened and it was stuck at that same error, i tried removing the song folder D:/Steam/steamapps/common/Quaver/Songs/7 - 525/ and reopening Quaver and it still wasn't working then i uninstalled and reinstalled Quaver but it's still stuck on this error

[10:39:47] - RUNTIME - ERROR: System.ArgumentException: Empty path name is not legal.
Parameter name: path
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at osu_database_reader.BinaryFiles.OsuDb.Read(String path)
   at Quaver.Shared.Database.Maps.MapDatabaseCache.JWjEgGtBBe()
   at Quaver.Shared.Database.Maps.MapDatabaseCache.OrderAndSetMapsets()
   at Quaver.Shared.Database.Maps.MapDatabaseCache.GWtMtq2PZs6IkokRoIoB()
   at Quaver.Shared.Database.Maps.MapDatabaseCache.Load(Boolean fullSync)
   at Quaver.Shared.QuaverGame.l3qEsP2PSqphMWmtDjg(Boolean fullSync)
   at Quaver.Shared.QuaverGame.btWbFn6Jr()
   at Quaver.Shared.QuaverGame.Initialize()
   at Microsoft.Xna.Framework.Game.DoInitialize()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Quaver.Program.Main()

**Comment by marcostudios** [comment]
I resolved by uninstalling Quaver, removing the leftover files and reinstalling Quaver, now importing works

**Comment by marcostudios** [comment]
Ok so i think it has something to do with enabling the "Load maps from other games" enabled and not having the osu path setted and then importing a map on Quaver.
