### ISSUE TITLE
Game Crashes when Custom Judgment Name is the same as the Preset

### ISSUE THREAD

**Issue by KaidenFrizu** [Quaver/Quaver#2659]
To reproduce the crash:
1. Rename your custom judgment to `Standard*` thus you have 2 of them. My timing windows on the custom judgment is the same as the ones on `Extreme` (Not sure if this is significant)
2. Play a chart using any of the 2 `Standard*` judgments.
3. Fail the chart midway
4. Click on `Convert Score` on Results Screen. Game Crashes

Notes:
Quaver does not stop when it crashes. See picture below.
![image](https://user-images.githubusercontent.com/39328974/94410609-1f87e580-01aa-11eb-84cf-68e857edcebd.png)

Logs:
```
[4:38:44] - RUNTIME - IMPORTANT: Skipping online score submission due to: due to failing on custom judgements
[4:38:45] - RUNTIME - IMPORTANT: Scheduled screen change to: 'Results'. w/ 1700 ms delay
[4:38:47] - RUNTIME - IMPORTANT: Changed to Screen 'Results'
[4:38:50] - RUNTIME - ERROR: System.ArgumentException: An item with the same key has already been added. Key: Standard*
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at Quaver.Shared.Screens.Results.UI.Footer.ConvertScoreRightClickOptions.GetOptions()
   at Quaver.Shared.Screens.Results.UI.Footer.ConvertScoreRightClickOptions..ctor(ResultsScreen screen)
   at Quaver.Shared.Screens.Results.UI.Footer.ResultsFooterConvertScoreButton.<>c__DisplayClass0_0.<.ctor>b__0(Object sender, EventArgs args)
   at Wobble.Graphics.UI.Buttons.Button.Update(GameTime gameTime)
   at Wobble.Graphics.Drawable.Update(GameTime gameTime)
[4:38:50] - RUNTIME - ERROR: System.NullReferenceException: Object reference not set to an instance of an object.
   at Quaver.Shared.Screens.Results.UI.Footer.ConvertScoreRightClickOptions.Destroy()
   at Wobble.Graphics.Drawable.Finalize()
```

**Comment by KaidenFrizu** [comment]
Follow-up: Quaver does not appear on Task Manager after the crash and consumes a lot of CPU and memory. Steam needs to be closed to close Quaver completely.

**Comment by EliteDreamer** [comment]
> Follow-up: Quaver does not appear on Task Manager after the crash and consumes a lot of CPU and memory. Steam needs to be closed to close Quaver completely.

For me the game just crashes without leaving any trace, same behaviour can be observed if you click on an already made score.

`[3:37:32] - RUNTIME - IMPORTANT: Fetched 6 Local scores for map: KRUX - Illusion of Inflict [Wonki's 4K Hyper] | Has PB: True
[3:37:33] - RUNTIME - IMPORTANT: Scheduled screen change to: 'Results'. w/ 0 ms delay
[3:37:33] - RUNTIME - IMPORTANT: Changed to Screen 'Results'
[3:37:34] - RUNTIME - ERROR: System.ArgumentException: An item with the same key has already been added. Key: Tough
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at Quaver.Shared.Screens.Results.UI.Footer.ConvertScoreRightClickOptions.GetOptions()
   at Quaver.Shared.Screens.Results.UI.Footer.ConvertScoreRightClickOptions..ctor(ResultsScreen screen)
   at Quaver.Shared.Screens.Results.UI.Footer.ResultsFooterConvertScoreButton.<>c__DisplayClass0_0.<.ctor>b__0(Object sender, EventArgs args)
   at Wobble.Graphics.UI.Buttons.Button.Update(GameTime gameTime)
   at Wobble.Graphics.Drawable.Update(GameTime gameTime)
[3:37:34] - RUNTIME - ERROR: System.NullReferenceException: Object reference not set to an instance of an object.
   at Quaver.Shared.Screens.Results.UI.Footer.ConvertScoreRightClickOptions.Destroy()
   at Wobble.Graphics.Drawable.Finalize()`
