### ISSUE TITLE
[wine] Hang on trying to open a map

### ISSUE THREAD

**Issue by YaLTeR** [Quaver/Quaver#285]
**Describe the bug**
Opening a map results in a hang on the black screen with the following messages in the terminal:
```
0172:fixme:bcrypt:BCryptCreateHash unimplemented flags 00000020
[8:26:12] - RUNTIME - ERROR: Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException: Unknown error (0xc1000002)
   at Internal.Cryptography.HashProviderCng..ctor(String hashAlgId, Byte[] key)
   at System.Security.Cryptography.MD5.Implementation..ctor()
   at System.Security.Cryptography.MD5.Create()
   at Quaver.Shared.Database.Maps.MapsetHelper.GetMd5Checksum(String path) in C:\Users\dog\GitSource\Quaver\Quaver.Shared\Database\Maps\MapsetHelper.cs:line 28
   at Quaver.Shared.Screens.Loading.MapLoadingScreen.LoadGameplayScreen() in C:\Users\dog\GitSource\Quaver\Quaver.Shared\Screens\Loading\MapLoadingScreen.cs:line 127
```
Closing the window works properly so it's not a complete hang.

**To Reproduce**
1. Open Quaver through wine with osu! maps.
2. Try opening a map in singleplayer.

**Expected behavior**
The map loads.

**Desktop (please complete the following information):**
- OS: Arch Linux x64
- wine 4.0 rc2 with a 64-bit prefix with Steam

**Comment by MarcPlaying** [comment]
Why wine when you can build directly to Linux 🤔

**Comment by YaLTeR** [comment]
Because it doesn't work yet: #270
