### ISSUE TITLE
Remove Prefer Wayland setting once SDL merges Wayland CSD

### ISSUE THREAD

**Issue by YaLTeR** [Quaver/Quaver#2880]
The Prefer Wayland setting exists only because SDL lacks Wayland CSD. Looks like someone's finally implementing it. When that happens Prefer Wayland should become the default behavior.

SDL issue (now that they've migrated to GitHub): https://github.com/libsdl-org/SDL/issues/3739
PR: https://github.com/libsdl-org/SDL/pull/4068

**Comment by YaLTeR** [comment]
SDL 2.0.16 has been released with the necessary changes. I spent several hours building it in the steam-runtime and trying to get it to work, but replacing our current SDL with 2.0.16 (either built in the steam-runtime, or from my Fedora 34 host) causes a very strange crash in coreclr which I've no idea how to debug:
```
#0  0x00007f7860aa2295 _ZN11MethodTable11IsICastableEv (libcoreclr.so + 0x113295)
#1  0x00007f7860ab9ead PreStubWorker (libcoreclr.so + 0x12aead)
#2  0x00007f7860bddf8c ThePreStub (libcoreclr.so + 0x24ef8c)
#3  0x00007f77e8a825ca n/a (n/a + 0x0)
#4  0x00007f77e8295ed6 n/a (n/a + 0x0)
#5  0x00007f77e8295ba9 n/a (n/a + 0x0)
#6  0x00007f77e8295ac1 n/a (n/a + 0x0)
#7  0x00007f77e77e2a50 n/a (n/a + 0x0)
#8  0x00007f77e77e07ae n/a (n/a + 0x0)
#9  0x00007f7860bdd2df CallDescrWorkerInternal (libcoreclr.so + 0x24e2df)
#10 0x00007f7860b0d3d5 _Z26CallDescrWorkerWithHandlerP13CallDescrDatai (libcoreclr.so + 0x17e3d5)
#11 0x00007f7860b0deb0 _ZN18MethodDescCallSite16CallTargetWorkerEPKmPmi (libcoreclr.so + 0x17eeb0)
#12 0x00007f7860bf1c52 _Z7RunMainP10MethodDescsPiPP8PtrArray (libcoreclr.so + 0x262c52)
#13 0x00007f7860bf1f50 _ZN8Assembly17ExecuteMainMethodEPP8PtrArrayi (libcoreclr.so + 0x262f50)
#14 0x00007f7860a5a011 _ZN8CorHost215ExecuteAssemblyEjPKDsiPS1_Pj (libcoreclr.so + 0xcb011)
#15 0x00007f7860a32d54 coreclr_execute_assembly (libcoreclr.so + 0xa3d54)
#16 0x00007f786113a333 n/a (libhostpolicy.so + 0x16333)
#17 0x00007f786113a6f4 n/a (libhostpolicy.so + 0x166f4)
#18 0x00007f786113adcc corehost_main (libhostpolicy.so + 0x16dcc)
#19 0x00007f786139ff1c n/a (libhostfxr.so + 0x2af1c)
#20 0x00007f786139eab3 n/a (libhostfxr.so + 0x29ab3)
#21 0x00007f7861399b03 hostfxr_main_startupinfo (libhostfxr.so + 0x24b03)
#22 0x000000000040f134 n/a (Quaver + 0xf134)
#23 0x000000000040f88e n/a (Quaver + 0xf88e)
#24 0x00007f7862dec062 n/a (/usr/lib/x86_64-linux-gnu/libc-2.31.so + 0x24062)
```
```
#0  MethodTable::GetFlag(MethodTable::WFLAGS_HIGH_ENUM) const (this=0x3, flag=MethodTable::enum_flag_ICastable) at /usr/src/debug/dotnet3.1-3.1.117-1.fc34.x86_64/src/coreclr.8fa8e21ba346527781651b2571f33d7a78422fcc/src/vm/methodtable.h:3848
#1  MethodTable::IsICastable() (this=0x3) at /usr/src/debug/dotnet3.1-3.1.117-1.fc34.x86_64/src/coreclr.8fa8e21ba346527781651b2571f33d7a78422fcc/src/vm/methodtable.cpp:612
#2  0x00007fb47f3bfff2 in PreStubWorker(TransitionBlock*, MethodDesc*) (pTransitionBlock=<optimized out>, pMD=0x7fb40733ba80) at /usr/src/debug/dotnet3.1-3.1.117-1.fc34.x86_64/src/coreclr.8fa8e21ba346527781651b2571f33d7a78422fcc/src/vm/prestub.cpp:1748
#3  0x00007fb47f4facac in ThePreStub () at /usr/src/debug/dotnet3.1-3.1.117-1.fc34.x86_64/src/coreclr.8fa8e21ba346527781651b2571f33d7a78422fcc/src/vm/amd64/theprestubamd64.S:17
#4  0x00007fb40741a93a in  ()
#5  0x00007fb3e011ab50 in  ()
#6  0x00007fb3e0117848 in  ()
#7  0x00007fb3e01167e0 in  ()
#8  0x000055f6ea6e2260 in  ()
#9  0x00007fb3e011ab50 in  ()
#10 0x0000000000100002 in  ()
#11 0x0000000000000000 in  ()
```
The crash doesn't happen when using the x11 platform, too. Might be some memory corruption but I'm not sure how to find what exactly goes wrong.

So the work isn't lost, I'm attaching SDL 2.0.16 built with Wayland and libdecor support in the steam-runtime: [SDL2-steam-runtime.zip](https://github.com/Quaver/Quaver/files/7006071/SDL2-steam-runtime.zip)

**Comment by YaLTeR** [comment]
SDL 2.0.22 switched to Wayland by default: https://github.com/libsdl-org/SDL/pull/4306
