### ISSUE TITLE
Random crash after starting a map in mp

### ISSUE THREAD

**Issue by YaLTeR** [Quaver/Quaver#2939]
```
[4:18:16] - RUNTIME - ERROR: System.NullReferenceException: Object reference not set to an instance of an object.
   at Quaver.Shared.Screens.Gameplay.Rulesets.Keys.HitObjects.HitObjectManagerKeys.get_ScrollSpeed() in /var/home/yalter/source/cs/Quaver/Quaver.Shared/Screens/Gameplay/Rulesets/Keys/HitObjects/HitObjectManagerKeys.cs:line 53
   at Quaver.Shared.Screens.Gameplay.Rulesets.Keys.Playfield.Lines.TimingLine.UpdateSpritePosition(Int64 offset) in /var/home/yalter/source/cs/Quaver/Quaver.Shared/Screens/Gameplay/Rulesets/Keys/Playfield/Lines/TimingLine.cs:line 74
   at Quaver.Shared.Screens.Gameplay.Rulesets.Keys.Playfield.Lines.TimingLineManager.UpdateObjectPool() in /var/home/yalter/source/cs/Quaver/Quaver.Shared/Screens/Gameplay/Rulesets/Keys/Playfield/Lines/TimingLineManager.cs:line 158
   at Quaver.Shared.Screens.Gameplay.Rulesets.Keys.GameplayRulesetKeys.Update(GameTime gameTime) in /var/home/yalter/source/cs/Quaver/Quaver.Shared/Screens/Gameplay/Rulesets/Keys/GameplayRulesetKeys.cs:line 111
   at Quaver.Shared.Screens.Gameplay.GameplayScreenView.Update(GameTime gameTime) in /var/home/yalter/source/cs/Quaver/Quaver.Shared/Screens/Gameplay/GameplayScreenView.cs:line 336
   at Wobble.Screens.Screen.Update(GameTime gameTime) in /var/home/yalter/source/cs/Quaver/Wobble/Wobble/Screens/Screen.cs:line 25
   at Quaver.Shared.Screens.QuaverScreen.Update(GameTime gameTime) in /var/home/yalter/source/cs/Quaver/Quaver.Shared/Screens/QuaverScreen.cs:line 92
   at Quaver.Shared.Screens.Gameplay.GameplayScreen.Update(GameTime gameTime) in /var/home/yalter/source/cs/Quaver/Quaver.Shared/Screens/Gameplay/GameplayScreen.cs:line 516
   at Wobble.Screens.ScreenManager.Update(GameTime gameTime) in /var/home/yalter/source/cs/Quaver/Wobble/Wobble/Screens/ScreenManager.cs:line 86
   at Wobble.WobbleGame.Update(GameTime gameTime) in /var/home/yalter/source/cs/Quaver/Wobble/Wobble/WobbleGame.cs:line 196
   at Quaver.Shared.QuaverGame.Update(GameTime gameTime) in /var/home/yalter/source/cs/Quaver/Quaver.Shared/QuaverGame.cs:line 338
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in /var/home/yalter/source/cs/Quaver/Wobble/MonoGame/MonoGame.Framework/Game.cs:line 686
   at Microsoft.Xna.Framework.Game.Tick() in /var/home/yalter/source/cs/Quaver/Wobble/MonoGame/MonoGame.Framework/Game.cs:line 527
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in /var/home/yalter/source/cs/Quaver/Wobble/MonoGame/MonoGame.Framework/Platform/SDL/SDLGamePlatform.cs:line 430
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in /var/home/yalter/source/cs/Quaver/Wobble/MonoGame/MonoGame.Framework/Game.cs:line 424
   at Microsoft.Xna.Framework.Game.Run() in /var/home/yalter/source/cs/Quaver/Wobble/MonoGame/MonoGame.Framework/Game.cs:line 394
   at Quaver.Program.Run() in /var/home/yalter/source/cs/Quaver/Quaver/Program.cs:line 113
   at Quaver.Program.Main(String[] args) in /var/home/yalter/source/cs/Quaver/Quaver/Program.cs:line 63
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Quaver.Shared.Screens.Gameplay.Rulesets.Keys.HitObjects.HitObjectManagerKeys.get_ScrollSpeed() in /var/home/yalter/source/cs/Quaver/Quaver.Shared/Screens/Gameplay/Rulesets/Keys/HitObjects/HitObjectManagerKeys.cs:line 53
   at Quaver.Shared.Screens.Gameplay.Rulesets.Keys.Playfield.Lines.TimingLine.UpdateSpritePosition(Int64 offset) in /var/home/yalter/source/cs/Quaver/Quaver.Shared/Screens/Gameplay/Rulesets/Keys/Playfield/Lines/TimingLine.cs:line 74
   at Quaver.Shared.Screens.Gameplay.Rulesets.Keys.Playfield.Lines.TimingLineManager.UpdateObjectPool() in /var/home/yalter/source/cs/Quaver/Quaver.Shared/Screens/Gameplay/Rulesets/Keys/Playfield/Lines/TimingLineManager.cs:line 158
   at Quaver.Shared.Screens.Gameplay.Rulesets.Keys.GameplayRulesetKeys.Update(GameTime gameTime) in /var/home/yalter/source/cs/Quaver/Quaver.Shared/Screens/Gameplay/Rulesets/Keys/GameplayRulesetKeys.cs:line 111
   at Quaver.Shared.Screens.Gameplay.GameplayScreenView.Update(GameTime gameTime) in /var/home/yalter/source/cs/Quaver/Quaver.Shared/Screens/Gameplay/GameplayScreenView.cs:line 336
   at Wobble.Screens.Screen.Update(GameTime gameTime) in /var/home/yalter/source/cs/Quaver/Wobble/Wobble/Screens/Screen.cs:line 25
   at Quaver.Shared.Screens.QuaverScreen.Update(GameTime gameTime) in /var/home/yalter/source/cs/Quaver/Quaver.Shared/Screens/QuaverScreen.cs:line 92
   at Quaver.Shared.Screens.Gameplay.GameplayScreen.Update(GameTime gameTime) in /var/home/yalter/source/cs/Quaver/Quaver.Shared/Screens/Gameplay/GameplayScreen.cs:line 516
   at Wobble.Screens.ScreenManager.Update(GameTime gameTime) in /var/home/yalter/source/cs/Quaver/Wobble/Wobble/Screens/ScreenManager.cs:line 86
   at Wobble.WobbleGame.Update(GameTime gameTime) in /var/home/yalter/source/cs/Quaver/Wobble/Wobble/WobbleGame.cs:line 196
   at Quaver.Shared.QuaverGame.Update(GameTime gameTime) in /var/home/yalter/source/cs/Quaver/Quaver.Shared/QuaverGame.cs:line 338
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in /var/home/yalter/source/cs/Quaver/Wobble/MonoGame/MonoGame.Framework/Game.cs:line 686
   at Microsoft.Xna.Framework.Game.Tick() in /var/home/yalter/source/cs/Quaver/Wobble/MonoGame/MonoGame.Framework/Game.cs:line 527
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in /var/home/yalter/source/cs/Quaver/Wobble/MonoGame/MonoGame.Framework/Platform/SDL/SDLGamePlatform.cs:line 430
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in /var/home/yalter/source/cs/Quaver/Wobble/MonoGame/MonoGame.Framework/Game.cs:line 424
   at Microsoft.Xna.Framework.Game.Run() in /var/home/yalter/source/cs/Quaver/Wobble/MonoGame/MonoGame.Framework/Game.cs:line 394
   at Quaver.Program.Run() in /var/home/yalter/source/cs/Quaver/Quaver/Program.cs:line 113
   at Quaver.Program.Main(String[] args) in /var/home/yalter/source/cs/Quaver/Quaver/Program.cs:line 63
```

**Comment by YaLTeR** [comment]
ah, this must be one of the threading issues i suppose
