### ISSUE TITLE
Quaver does not open 

### ISSUE THREAD

**Issue by Puumpkin** [Quaver/Quaver#3094]
**Describe the bug**
When I try and open the game steam says it is running for 3 seconds and then crashes. The game never opens and it has been happening for the past few days. 

**To Reproduce**
1. Go to steam
2. Click on play
3. See error

**Expected behavior**
It opens and I can play the game.

**Comment by Puumpkin** [comment]
Log:
 
[4:41:03] - RUNTIME - DEBUG: OS: Microsoft Windows 10.0.22000
[4:41:03] - RUNTIME - IMPORTANT: Config file has been successfully read.
[4:41:04] - RUNTIME - IMPORTANT: Started IPC server on port: 43596
[4:41:04] - RUNTIME - IMPORTANT: Successfully initialized and logged into Steam as : Pumpkin <76561198051018850>
[4:41:04] - RUNTIME - IMPORTANT: Found 0 subscribed workshop items | # of subscribed: 10 | Entries: 1
[4:41:07] - RUNTIME - DEBUG: BASS options: DevicePeriod = -1, DeviceBufferLength = 8
[4:41:07] - RUNTIME - ERROR: Wobble.Audio.AudioEngineException: BASS has failed to initialize (error code: 46, name: "Busy")! Are your platform-specific dlls present?
   at Wobble.Audio.AudioManager.Initialize(Nullable`1 devicePeriod, Nullable`1 deviceBufferLength) in C:\Quaver\Wobble\Wobble\Audio\AudioManager.cs:line 54
   at Wobble.WobbleGame.Initialize() in C:\Quaver\Wobble\Wobble\WobbleGame.cs:line 147
   at Quaver.Shared.QuaverGame.Initialize() in C:\Quaver\Quaver.Shared\QuaverGame.cs:line 292
   at Microsoft.Xna.Framework.Game.DoInitialize() in C:\Quaver\Wobble\MonoGame\MonoGame.Framework\Game.cs:line 715
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in C:\Quaver\Wobble\MonoGame\MonoGame.Framework\Game.cs:line 409
   at Microsoft.Xna.Framework.Game.Run() in C:\Quaver\Wobble\MonoGame\MonoGame.Framework\Game.cs:line 395
   at Quaver.Program.Run() in C:\Quaver\Quaver\Program.cs:line 114
   at Quaver.Program.Main(String[] args) in C:\Quaver\Quaver\Program.cs:line 63
