### ISSUE TITLE
The game crashes after it starts

### ISSUE THREAD

**Issue by prcups** [Quaver/Quaver#3267]
I use Arch Linux and the kernel is 5.14.8-zen. The game crashes just after it is started by Steam. The log said:
```
[1:36:45] - RUNTIME - DEBUG: OS: Linux 5.14.8-zen1-1-zen #1 ZEN SMP PREEMPT Sun, 26 Sep 2021 19:36:16 +0000
[1:36:45] - RUNTIME - IMPORTANT: Config file has been successfully read.
[1:36:45] - RUNTIME - IMPORTANT: Started IPC server on port: 43596
[1:36:45] - RUNTIME - IMPORTANT: Successfully initialized and logged into Steam as : Yuno <76561199063399395>
[1:36:45] - RUNTIME - IMPORTANT: Found 0 subscribed workshop items | # of subscribed: 0 | Entries: 0
[1:36:45] - RUNTIME - DEBUG: BASS options: DevicePeriod = 2, DeviceBufferLength = 8
[1:36:45] - RUNTIME - ERROR: Wobble.Audio.AudioEngineException: BASS has failed to initialize (error code: 3, name: "Driver")! Are your platform-specific dlls present?
   at Wobble.Audio.AudioManager.Initialize(Nullable`1 devicePeriod, Nullable`1 deviceBufferLength) in C:\Quaver\Wobble\Wobble\Audio\AudioManager.cs:line 54
   at Wobble.WobbleGame.Initialize() in C:\Quaver\Wobble\Wobble\WobbleGame.cs:line 147
   at Quaver.Shared.QuaverGame.Initialize() in C:\Quaver\Quaver.Shared\QuaverGame.cs:line 292
   at Microsoft.Xna.Framework.Game.DoInitialize() in C:\Quaver\Wobble\MonoGame\MonoGame.Framework\Game.cs:line 715
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in C:\Quaver\Wobble\MonoGame\MonoGame.Framework\Game.cs:line 409
   at Microsoft.Xna.Framework.Game.Run() in C:\Quaver\Wobble\MonoGame\MonoGame.Framework\Game.cs:line 395
   at Quaver.Program.Run() in C:\Quaver\Quaver\Program.cs:line 114
   at Quaver.Program.Main(String[] args) in C:\Quaver\Quaver\Program.cs:line 63
```

**Comment by Swan** [comment]
Try looking through these issues, they probably have a solution to your problem already. If not, open again.
https://github.com/Quaver/Quaver/issues?q=is%3Aissue+linux+is%3Aclosed
