### ISSUE TITLE
[Chat] Overlapping text

### ISSUE THREAD

**Issue by Janko5** [Quaver/Quaver#3298]
Just like in the title.

I think that applies to it
runtime.log
```[11:33:59] - RUNTIME - IMPORTANT: Fetching message history for channel: #offtopic
[11:33:59] - RUNTIME - IMPORTANT: Finished Fetching message history for channel: #offtopic w/ 20 messages!
[11:33:59] - RUNTIME - ERROR: System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at Quaver.Shared.Graphics.Overlays.Chatting.Messages.Scrolling.ChatMessageScrollContainer.FlushMessageHistoryQueue() in C:\Quaver\Quaver.Shared\Graphics\Overlays\Chatting\Messages\Scrolling\ChatMessageScrollContainer.cs:line 214
   at Quaver.Shared.Graphics.Overlays.Chatting.Messages.Scrolling.ChatMessageScrollContainer.Update(GameTime gameTime) in C:\Quaver\Quaver.Shared\Graphics\Overlays\Chatting\Messages\Scrolling\ChatMessageScrollContainer.cs:line 123
   at Wobble.Graphics.Drawable.Update(GameTime gameTime)
[11:33:59] - RUNTIME - IMPORTANT: Flushed 20 messages from the `#offtopic` message history queue.
[11:34:27] - RUNTIME - IMPORTANT: Fetching message history for channel: #quaver
[11:34:27] - RUNTIME - IMPORTANT: Finished Fetching message history for channel: #quaver w/ 20 messages!
[11:34:27] - RUNTIME - IMPORTANT: Flushed 20 messages from the `#quaver` message history queue.```

![](https://cdn.discordapp.com/attachments/541616236316852244/905587009190514708/1132021_23-35-20-591.jpg)

**Comment by YaLTeR** [comment]
I haven't seen it happen with #3302 after a few days of multi so I'm pretty confident it's fixed.
