### ISSUE TITLE
Quaver not starting

### ISSUE THREAD

**Issue by verarr** [Quaver/Quaver#3455]
Quaver immediately stops after clicking 'Play' on Steam.

**To Reproduce**
1. Run Quaver
2. Steam displays running for a moment
3. Game stops

**Expected behavior**
The game starts.

**Desktop:**
 - OS: Pop!_OS 22.04 LTS x86_64 (kernel: `5.16.19-76051619-generic`)
 - Game Version: Steam latest
 - Audio server: pipewire (with pipewire-pulse installed; this might be relevant)

**Additional context**
I think this issue might be caused by pipewire replacing pulseaudio as `runtime.log` suggests something is wrong with audio:
```
[--:--:--] - RUNTIME - DEBUG: OS: Linux 5.16.19-76051619-generic #------------~----------~22.04~------- SMP PREEMPT Mon Apr 11 17
[--:--:--] - RUNTIME - IMPORTANT: Config file has been successfully read.
[--:--:--] - RUNTIME - IMPORTANT: Started IPC server on port: 4--96
[--:--:--] - RUNTIME - IMPORTANT: Successfully initialized and logged into Steam as : --- <----------------->
[--:--:--] - RUNTIME - IMPORTANT: Found 0 subscribed workshop items | # of subscribed: 2 | Entries: 1
[--:--:--] - RUNTIME - DEBUG: BASS options: DevicePeriod = 2, DeviceBufferLength = 8
[--:--:--] - RUNTIME - ERROR: Wobble.Audio.AudioEngineException: BASS has failed to initialize (error code: 3, name: "Driver")! Are your platform-specific dlls present?
   at Wobble.Audio.AudioManager.Initialize(Nullable`1 devicePeriod, Nullable`1 deviceBufferLength) in C:\Quaver\Wobble\Wobble\Audio\AudioManager.cs:line 54
   at Wobble.WobbleGame.Initialize() in C:\Quaver\Wobble\Wobble\WobbleGame.cs:line 147
   at Quaver.Shared.QuaverGame.Initialize() in C:\Quaver\Quaver.Shared\QuaverGame.cs:line 292
   at Microsoft.Xna.Framework.Game.DoInitialize() in C:\Quaver\Wobble\MonoGame\MonoGame.Framework\Game.cs:line 715
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in C:\Quaver\Wobble\MonoGame\MonoGame.Framework\Game.cs:line 409
   at Microsoft.Xna.Framework.Game.Run() in C:\Quaver\Wobble\MonoGame\MonoGame.Framework\Game.cs:line 395
   at Quaver.Program.Run() in C:\Quaver\Quaver\Program.cs:line 114
   at Quaver.Program.Main(String[] args) in C:\Quaver\Quaver\Program.cs:line 63
```
It also seems like it's running inside a wine (or proton) prefix, but I thought the game ran natively?

**Comment by Swan** [comment]
The common solution is to run it on steam from flathub. Open back up if it's still not working
