### ISSUE TITLE
Can't convert map from o!m

### ISSUE THREAD

**Issue by Enn3Developer** [Quaver/Quaver#3563]
**Describe the bug**
Trying to convert a map by dragging it on the game it fails

**To Reproduce**
1. Download an o!m map
2. Open Quaver
3. Open the file manager and drag the map on to Quaver
4. Click on Single player on Quaver (to start the conversion process)
5. The conversion fails

**Expected behavior**
It should convert the map as it was the previous version

**Log**
This is the relevant part of the log:
```
[8:14:06] - RUNTIME - IMPORTANT: Scheduled screen change to: 'Importing'. w/ 0 ms delay
[8:14:07] - RUNTIME - IMPORTANT: Changed to Screen 'Importing'
[8:14:07] - RUNTIME - ERROR: System.IO.DirectoryNotFoundException: Could not find a part of the path '/home/enn3/Downloads/1760510 Noah - The End.osz'.
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileInfo.OpenRead()
   at SharpCompress.Archives.ArchiveFactory.Open(FileInfo fileInfo, ReaderOptions options)
   at SharpCompress.Archives.ArchiveFactory.Open(String filePath, ReaderOptions options)
   at Quaver.Shared.Converters.Osu.Osu.ConvertOsz(String file, String extractDirectory) in C:\Quaver\Quaver.Shared\Converters\Osu\Osu.cs:line 30
[8:14:07] - RUNTIME - ERROR: System.IO.DirectoryNotFoundException: Could not find a part of the path '/home/enn3/Downloads/1760510 Noah - The End.osz'.
   at System.IO.FileSystem.DeleteFile(String fullPath)
   at System.IO.File.Delete(String path)
   at Quaver.Shared.Database.Maps.MapsetImporter.<>c__DisplayClass12_0.<ImportMapsetsInQueue>b__0(Int32 i) in C:\Quaver\Quaver.Shared\Database\Maps\MapsetImporter.cs:line 319
```

**Desktop (please complete the following information):**
 - OS: Solus (Linux)
 - Quaver Version: 0.32.2

**Comment by AiAe** [comment]
Is it just this specific mapset if yes please provide link for download, if not give us more information on how you run Steam/Quaver.

**Comment by Enn3Developer** [comment]
It isn't just a single mapset (else I would've shared the link).
I'm running Steam from flatpak and Quaver runs natively (**not** with Proton)

**Comment by Enn3Developer** [comment]
It worked, thanks!
