### ISSUE TITLE
Can't run Quaver when installed through Steam on a separate drive

### ISSUE THREAD

**Issue by itsMapleLeaf** [Quaver/Quaver#3712]
**Describe the bug**
I have a C:\ drive, which is the main windows drive, and a separate D:\ drive, where I install all my steam games. Quaver runs when on C:\, but when installed on D:\, clicking "Play" does nothing

**To Reproduce**
1. Have a separate drive
2. Steam > Quaver > Properties > Local Files > Move to external drive
3. Click "Play". The button says "starting" for a bit, but nothing happens
4. Steam > Quaver > Properties > Local Files > Move to local drive
5. Click "Play". Quaver opens

**Expected behavior**
Quaver should open when installed on a separate drive

**Screenshots**
https://user-images.githubusercontent.com/19603573/206568334-4ff5be6a-4185-4c49-b903-92eb7f89082d.mp4

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Edge
 - Version: 0.32.0 (it says 1.0.0 in the title bar?)

**Additional context**
- Uninstalling and reinstalling to D:\ instead of moving does not help
- Also happens w/ Canary
- Log:
   ```log
   [3:21:23] - RUNTIME - DEBUG: OS: Microsoft Windows 10.0.22621
   [3:21:23] - RUNTIME - IMPORTANT: Config file has been successfully read.
   [3:21:23] - RUNTIME - IMPORTANT: Started IPC server on port: 43596
   [3:21:24] - RUNTIME - ERROR: System.DllNotFoundException: Unable to load DLL 'steam_api64' or one of its dependencies: The specified module could not be found. (0x8007007E)
      at Steamworks.NativeMethods.SteamAPI_RestartAppIfNecessary(AppId_t unOwnAppID)
      at Steamworks.SteamAPI.RestartAppIfNecessary(AppId_t unOwnAppID)
      at Quaver.Shared.Online.SteamManager.Initialize() in C:\Quaver\Quaver.Shared\Online\SteamManager.cs:line 103
      at Quaver.Program.Run() in C:\Quaver\Quaver\Program.cs:line 98
      at Quaver.Program.Main(String[] args) in C:\Quaver\Quaver\Program.cs:line 63
   ```
- The dll file does exist:
  ![image](https://user-images.githubusercontent.com/19603573/206571262-e77f5436-74b5-4f35-8214-82c52267d833.png)

**Comment by AiAe** [comment]
Tried to move my game from C to D drive and the game still works.
Is your D drive actually different drive in your system or its partition? 
Because if its different drive i cannot test that case.

**Comment by itsMapleLeaf** [comment]
It's a different drive, NTFS format, 1TB

**Comment by AiAe** [comment]
Hopefully someone else can test and verify this. 
Still does not make sense to cause such issue
