### ISSUE TITLE
Maps not loading correctly on Ubuntu 23.04

### ISSUE THREAD

**Issue by notlunar454** [Quaver/Quaver#3918]
### Describe the bug

Map consistently freezes just before a second has elapsed in every map. Was working fine on Ubuntu 22.04, but upgrading seems to have broken support. I'm running on Ubuntu 23.04 with x11. Controls still function however alt+f4 just crashes quaver. I have cleared quaver.db and refreshed all maps, and tweaked settings. Screenshot shows exactly how it freezes

### To Reproduce

1. Open a map on Ubuntu 23.04 W/ x11

### Log Files

[6:27:11] - RUNTIME - DEBUG: OS: Linux 6.2.0-34-generic #34-Ubuntu SMP PREEMPT_DYNAMIC Mon Sep  4 13:06:55 UTC 2023
[6:27:12] - RUNTIME - IMPORTANT: Config file has been successfully read.
[6:27:12] - RUNTIME - IMPORTANT: Started IPC server on port: 43596
[6:27:12] - RUNTIME - IMPORTANT: Successfully initialized and logged into Steam as : lunar454 <76561199538769849>
[6:27:12] - RUNTIME - IMPORTANT: Found 0 subscribed workshop items | # of subscribed: 1 | Entries: 1
[6:27:13] - RUNTIME - DEBUG: BASS options: DevicePeriod = 2, DeviceBufferLength = 8
[6:27:13] - RUNTIME - DEBUG: BASS version: 2.4.13.8
[6:27:15] - RUNTIME - DEBUG: Currently running Quaver version: `1.2.0`
[6:27:15] - RUNTIME - IMPORTANT: Scheduled Screen Change
[6:27:15] - RUNTIME - IMPORTANT: Screen has been switched to type: `Initialization`
[6:27:15] - RUNTIME - IMPORTANT: Loading skin...
[6:27:17] - RUNTIME - IMPORTANT: Loading fonts...
[6:27:17] - RUNTIME - DEBUG: Loaded font: Lato-Regular
[6:27:17] - RUNTIME - DEBUG: Loaded font: Lato-Semibold
[6:27:17] - RUNTIME - DEBUG: Loaded font: Lato-Bold
[6:27:17] - RUNTIME - DEBUG: Loaded font: Lato-Light
[6:27:17] - RUNTIME - DEBUG: Loaded font: Lato-Heavy
[6:27:17] - RUNTIME - DEBUG: Loaded font: Lato-Black
[6:27:18] - RUNTIME - IMPORTANT: Performing game initialization task... 

### Screenshots

![image](https://github.com/Quaver/Quaver/assets/120600491/4809032b-1859-4d2a-be58-f387815045c8)

**Comment by Warp9000** [comment]
What exactly isnt loading correctly?

Can you also send the entire log files.

**Comment by notlunar454** [comment]
Screen looks pretty much exactly like that screenshot. Note freeze and do not fall down, timer does not increment, health does not drop. FPS counter does update correctly.
Full log:
`[7:34:14] - RUNTIME - DEBUG: OS: Linux 6.2.0-34-generic #34-Ubuntu SMP PREEMPT_DYNAMIC Mon Sep  4 13:06:55 UTC 2023
[7:34:15] - RUNTIME - IMPORTANT: Config file has been successfully read.
[7:34:15] - RUNTIME - IMPORTANT: Started IPC server on port: 43596
[7:34:15] - RUNTIME - IMPORTANT: Successfully initialized and logged into Steam as : lunar454 <76561199538769849>
[7:34:15] - RUNTIME - IMPORTANT: Found 0 subscribed workshop items | # of subscribed: 1 | Entries: 1
[7:34:16] - RUNTIME - DEBUG: BASS options: DevicePeriod = 2, DeviceBufferLength = 8
[7:34:16] - RUNTIME - DEBUG: BASS version: 2.4.13.8
[7:34:18] - RUNTIME - DEBUG: Currently running Quaver version: `1.2.0`
[7:34:18] - RUNTIME - IMPORTANT: Scheduled Screen Change
[7:34:18] - RUNTIME - IMPORTANT: Screen has been switched to type: `Initialization`
[7:34:18] - RUNTIME - IMPORTANT: Loading skin...
[7:34:21] - RUNTIME - IMPORTANT: Loading fonts...
[7:34:21] - RUNTIME - DEBUG: Loaded font: Lato-Regular
[7:34:21] - RUNTIME - DEBUG: Loaded font: Lato-Semibold
[7:34:21] - RUNTIME - DEBUG: Loaded font: Lato-Bold
[7:34:21] - RUNTIME - DEBUG: Loaded font: Lato-Light
[7:34:21] - RUNTIME - DEBUG: Loaded font: Lato-Heavy
[7:34:21] - RUNTIME - DEBUG: Loaded font: Lato-Black
[7:34:21] - RUNTIME - IMPORTANT: Performing game initialization task... 
[7:34:21] - RUNTIME - IMPORTANT: Scores table has been created
[7:34:21] - RUNTIME - IMPORTANT: Map Database has been created
[7:34:21] - RUNTIME - IMPORTANT: Found 72 .qua files inside the song directory
[7:34:21] - RUNTIME - IMPORTANT: Playlist Table has been created
[7:34:21] - RUNTIME - IMPORTANT: PlaylistMap table has been created
[7:34:21] - RUNTIME - IMPORTANT: QuaverSettings table has been created
[7:34:21] - RUNTIME - IMPORTANT: Found 0 maps that have outdated difficulty ratings. Scheduling recalculation upon enteringselect.
[7:34:21] - RUNTIME - IMPORTANT: JudgementWindows table has been created
[7:34:21] - RUNTIME - IMPORTANT: Created preset judgement windows `Standard*` - Marv: 18 | Perf: 43 | Great: 76 | Good: 106 | Okay: 127 | Miss: 164
[7:34:21] - RUNTIME - IMPORTANT: Created preset judgement windows `Peaceful` - Marv: 23 | Perf: 57 | Great: 101 | Good: 141 | Okay: 169 | Miss: 218
[7:34:21] - RUNTIME - IMPORTANT: Created preset judgement windows `Lenient` - Marv: 21 | Perf: 52 | Great: 91 | Good: 128 | Okay: 153 | Miss: 198
[7:34:21] - RUNTIME - IMPORTANT: Created preset judgement windows `Chill` - Marv: 19 | Perf: 47 | Great: 83 | Good: 116 | Okay: 139 | Miss: 180
[7:34:21] - RUNTIME - IMPORTANT: Created preset judgement windows `Strict` - Marv: 16 | Perf: 39 | Great: 69 | Good: 96 | Okay: 127 | Miss: 164
[7:34:21] - RUNTIME - IMPORTANT: Created preset judgement windows `Tough` - Marv: 14 | Perf: 35 | Great: 62 | Good: 87 | Okay: 127 | Miss: 164
[7:34:21] - RUNTIME - IMPORTANT: Created preset judgement windows `Extreme` - Marv: 13 | Perf: 32 | Great: 57 | Good: 79 | Okay: 127 | Miss: 164
[7:34:21] - RUNTIME - IMPORTANT: Created preset judgement windows `Impossible` - Marv: 8 | Perf: 20 | Great: 35 | Good: 49 | Okay: 127 | Miss: 164
[7:34:21] - RUNTIME - IMPORTANT: UserProfile table has been created
[7:34:22] - RUNTIME - IMPORTANT: Game initialization task complete!
[7:34:22] - RUNTIME - IMPORTANT: Scheduled Screen Change
[7:34:27] - RUNTIME - IMPORTANT: Screen `Menu` has been loaded proceeding to switch.
[7:34:27] - RUNTIME - IMPORTANT: Screen has been switched to type: `Menu`
[7:34:28] - RUNTIME - DEBUG: Selected new jukebox track (0): Plum - Fantasy Collision [Normal] 
[7:34:29] - RUNTIME - IMPORTANT: Scheduled Screen Change
[7:34:30] - RUNTIME - ERROR: System.Net.WebException: The SSL connection could not be established, see inner exception.
 ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.IO.IOException: Unable to read data from the transport connection: Connection reset by peer.
 ---> System.Net.Sockets.SocketException (104): Connection reset by peer
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Security.SslStream.<FillHandshakeBufferAsync>g__InternalFillHandshakeBufferAsync|189_0[TIOAdapter](TIOAdapter adap, ValueTask`1 task, Int32 minSize)
   at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellation(CancellationToken cancellationToken)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageHandlerStage.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageHandlerStage.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.SocketsHttpHandler.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageInvoker.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.Send(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at System.Net.HttpWebRequest.SendRequest(Boolean async)
   at System.Net.HttpWebRequest.GetResponse()
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetResponse()
   at System.Net.WebClient.GetWebResponse(WebRequest request)
   at System.Net.WebClient.DownloadBits(WebRequest request, Stream writeStream)
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at System.Net.WebClient.DownloadData(String address)
   at Quaver.Shared.Online.API.News.APIRequestNewsFeed.LoadBanner(APIResponseNewsFeed feed) in D:\QuaverDeploy\Quaver\Quaver.Shared\Online\API\News\APIRequestNewsPost.cs:line 57
[7:34:31] - RUNTIME - IMPORTANT: ---- Health Weighting ----
[7:34:31] - RUNTIME - IMPORTANT: Marv: 1
[7:34:31] - RUNTIME - IMPORTANT: Perf: 0.97
[7:34:31] - RUNTIME - IMPORTANT: Great: 0.4
[7:34:31] - RUNTIME - IMPORTANT: Good: -1.21
[7:34:31] - RUNTIME - IMPORTANT: Okay: -1.91
[7:34:31] - RUNTIME - IMPORTANT: Miss: -6
[7:34:31] - RUNTIME - IMPORTANT: Screen `Select` has been loaded proceeding to switch.
[7:34:31] - RUNTIME - IMPORTANT: Fetched 0 Global scores for map: Plum - Fantasy Collision [Normal] | Has PB: False
[7:34:32] - RUNTIME - IMPORTANT: Cleared previously available chat channels
[7:34:32] - RUNTIME - IMPORTANT: Received Twitch Connection Status: Connected: False | Username: 
[7:34:32] - RUNTIME - IMPORTANT: Received available chat channel: #quaver
[7:34:32] - RUNTIME - IMPORTANT: Joined chat channel: #quaver | General discussion about Quaver
[7:34:32] - RUNTIME - IMPORTANT: Received available chat channel: #first-places
[7:34:32] - RUNTIME - IMPORTANT: Joined chat channel: #first-places | Players who achieve first place on a map are shown here
[7:34:32] - RUNTIME - IMPORTANT: Received friends list containing 0 users.
[7:34:32] - RUNTIME - IMPORTANT: Screen has been switched to type: `Select`
[7:34:34] - RUNTIME - DEBUG: Updated map: 847bcf602559d8e1eb576e622cf3e748 (#21) in the cache
[7:34:34] - RUNTIME - IMPORTANT: Fetched 50 Global scores for map: Plum - Fantasy Collision [Normal] | Has PB: True
[7:34:36] - RUNTIME - IMPORTANT: ---- Health Weighting ----
[7:34:36] - RUNTIME - IMPORTANT: Marv: 1.17
[7:34:36] - RUNTIME - IMPORTANT: Perf: 1.17
[7:34:36] - RUNTIME - IMPORTANT: Great: 0.47
[7:34:36] - RUNTIME - IMPORTANT: Good: -0.58
[7:34:36] - RUNTIME - IMPORTANT: Okay: -0.99
[7:34:36] - RUNTIME - IMPORTANT: Miss: -6
[7:34:37] - RUNTIME - DEBUG: Updated map: 35d1e49cb0877f0212f2a2e0577205e5 (#62) in the cache
[7:34:37] - RUNTIME - IMPORTANT: Fetched 50 Global scores for map: HyuN - Princess of Winter [Easy] | Has PB: False
[7:34:38] - RUNTIME - IMPORTANT: Scheduled Screen Change
[7:34:38] - RUNTIME - IMPORTANT: Screen `Loading` has been loaded proceeding to switch.
[7:34:38] - RUNTIME - IMPORTANT: ---- Health Weighting ----
[7:34:38] - RUNTIME - IMPORTANT: Marv: 0.95
[7:34:38] - RUNTIME - IMPORTANT: Perf: 0.91
[7:34:38] - RUNTIME - IMPORTANT: Great: 0.38
[7:34:38] - RUNTIME - IMPORTANT: Good: -1.38
[7:34:38] - RUNTIME - IMPORTANT: Okay: -2.16
[7:34:38] - RUNTIME - IMPORTANT: Miss: -6
[7:34:38] - RUNTIME - IMPORTANT: Screen has been switched to type: `Loading`
[7:34:38] - RUNTIME - IMPORTANT: Scheduled Screen Change
[7:34:38] - RUNTIME - DEBUG: Updated map: 7bf37dba4c51f2119130f419120078c0 (#64) in the cache
[7:34:38] - RUNTIME - IMPORTANT: ---- Health Weighting ----
[7:34:38] - RUNTIME - IMPORTANT: Marv: 0.95
[7:34:38] - RUNTIME - IMPORTANT: Perf: 0.91
[7:34:38] - RUNTIME - IMPORTANT: Great: 0.38
[7:34:38] - RUNTIME - IMPORTANT: Good: -1.38
[7:34:38] - RUNTIME - IMPORTANT: Okay: -2.16
[7:34:38] - RUNTIME - IMPORTANT: Miss: -6
[7:34:39] - RUNTIME - DEBUG: Updated map: 7bf37dba4c51f2119130f419120078c0 (#64) in the cache
[7:34:39] - RUNTIME - IMPORTANT: Screen `Gameplay` has been loaded proceeding to switch.
[7:34:39] - RUNTIME - IMPORTANT: Screen has been switched to type: `Gameplay`
[7:34:55] - RUNTIME - IMPORTANT: Discord RPC has shutdown`

**Comment by AiAe** [comment]
Looks like you are maybe missing openssl? I don't remember the exact issue but some linux distros didn't have it. 
Which Linux are you using? 
Alternatively you can play Quaver + Steam from flatpak.
