### ISSUE TITLE
The game cannot run without non-free software (Steam)

### ISSUE THREAD

**Issue by squeaktoy** [Quaver/Quaver#3947]
### Describe the bug

I want to play this game, but it seems to depend on some non-free portions of the Steam API. This is really unfortunate for an open source project, and should be considered a bug.

### To Reproduce

1. `git clone https://github.com/Quaver/Quaver`
2. `git submodule update --recursive --init`
3. `dotnet-bin-6.0 build`
4. `dotnet-bin-6.0 run --project Quaver`

### Expected behavior

The game should run on a GNU/Linux system without non-free software.

### Log Files

[run.log](https://github.com/Quaver/Quaver/files/13861450/run.log)

**Comment by YaLTeR** [comment]
While it would be nice to have a Steam-free version, the unfortunate reality is that the current code is quite tangled up with Steam integration. This game's primary target is Steam, and we don't have the developer bandwidth to make Steamless Quaver a thing.

**Comment by Warp9000** [comment]
i made a fork without any online code 
https://github.com/Warp9000/Quaver/tree/offline
(yes i was bored)

**Comment by squeaktoy** [comment]
@Warp9000 okay with your fork I get a different error:
```
[11:45:21] - RUNTIME - DEBUG: OS: Linux 6.1.67-gentoo #1 SMP PREEMPT_DYNAMIC Fri Jan  5 02:08:49 CET 2024
[11:45:21] - NETWORK - DEBUG: OS: Linux 6.1.67-gentoo #1 SMP PREEMPT_DYNAMIC Fri Jan  5 02:08:49 CET 2024
[11:45:21] - RUNTIME - IMPORTANT: Config file has been successfully read.
[11:45:21] - RUNTIME - IMPORTANT: Started IPC server on port: 43596
[11:45:22] - RUNTIME - DEBUG: BASS options: DevicePeriod = 2, DeviceBufferLength = 8
[11:45:22] - RUNTIME - ERROR: Wobble.Audio.AudioEngineException: BASS has failed to initialize (error code: 3, name: "Driver")! Are your platform-specific dlls present?
   at Wobble.Audio.AudioManager.Initialize(Nullable`1 devicePeriod, Nullable`1 deviceBufferLength, Nullable`1 device) in /home/user/software/games-rhythm/Quaver/Wobble/Wobble/Audio/AudioManager.cs:line 56
   at Wobble.WobbleGame.Initialize() in /home/user/software/games-rhythm/Quaver/Wobble/Wobble/WobbleGame.cs:line 146
   at Quaver.Shared.QuaverGame.Initialize() in /home/user/software/games-rhythm/Quaver/Quaver.Shared/QuaverGame.cs:line 298
   at Microsoft.Xna.Framework.Game.DoInitialize() in /home/user/software/games-rhythm/Quaver/Wobble/MonoGame/MonoGame.Framework/Game.cs:line 708
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in /home/user/software/games-rhythm/Quaver/Wobble/MonoGame/MonoGame.Framework/Game.cs:line 408
   at Microsoft.Xna.Framework.Game.Run() in /home/user/software/games-rhythm/Quaver/Wobble/MonoGame/MonoGame.Framework/Game.cs:line 394
   at Quaver.Program.Run() in /home/user/software/games-rhythm/Quaver/Quaver/Program.cs:line 115
   at Quaver.Program.Main(String[] args) in /home/user/software/games-rhythm/Quaver/Quaver/Program.cs:line 63
Unhandled exception. Wobble.Audio.AudioEngineException: BASS has failed to initialize (error code: 3, name: "Driver")! Are your platform-specific dlls present?
   at Wobble.Audio.AudioManager.Initialize(Nullable`1 devicePeriod, Nullable`1 deviceBufferLength, Nullable`1 device) in /home/user/software/games-rhythm/Quaver/Wobble/Wobble/Audio/AudioManager.cs:line 56
   at Wobble.WobbleGame.Initialize() in /home/user/software/games-rhythm/Quaver/Wobble/Wobble/WobbleGame.cs:line 146
   at Quaver.Shared.QuaverGame.Initialize() in /home/user/software/games-rhythm/Quaver/Quaver.Shared/QuaverGame.cs:line 298
   at Microsoft.Xna.Framework.Game.DoInitialize() in /home/user/software/games-rhythm/Quaver/Wobble/MonoGame/MonoGame.Framework/Game.cs:line 708
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in /home/user/software/games-rhythm/Quaver/Wobble/MonoGame/MonoGame.Framework/Game.cs:line 408
   at Microsoft.Xna.Framework.Game.Run() in /home/user/software/games-rhythm/Quaver/Wobble/MonoGame/MonoGame.Framework/Game.cs:line 394
   at Quaver.Program.Run() in /home/user/software/games-rhythm/Quaver/Quaver/Program.cs:line 115
   at Quaver.Program.Main(String[] args) in /home/user/software/games-rhythm/Quaver/Quaver/Program.cs:line 63
```
I wonder why it's using BASS. BASS is proprietary and obsolete in open source software. libopenmpt has replaced libbass nowadays.

**Comment by AiAe** [comment]
Feel free to rewrite the whole game 👍🏻 and make PR
