### ISSUE TITLE
System.ObjectDisposedException

### ISSUE THREAD

**Issue by Adrriii** [Quaver/Quaver#418]
Unknown error, didn't have any impact but displayed a notification while in song selection.

[8:30:19] - RUNTIME - DEBUG: Updated map: f5c2fb9bdf21840e8a244bcce4fc794b (`#184`) in the cache
[8:30:19] - RUNTIME - ERROR: System.ObjectDisposedException: The CancellationTokenSource has been disposed.
   at System.Threading.CancellationTokenSource.ThrowObjectDisposedException()
   at Quaver.Shared.Screens.Select.UI.Leaderboard.LeaderboardContainer.F8CCxRNdrTc26bfuJZX(Object )
   at Quaver.Shared.Screens.Select.UI.Leaderboard.LeaderboardContainer.Gaps8gbeuH()
   at Quaver.Shared.Scheduling.ThreadScheduler.<>c__DisplayClass1_0.lNeSJqOAbci47Ns04lHf(Object )
   at Quaver.Shared.Scheduling.ThreadScheduler.<>c__DisplayClass1_0.<Run>b__0()
[8:30:20] - RUNTIME - DEBUG: Updated map: 0f0968865a87e03e893f34e1c10c23be (`#185`) in the cache

**Comment by Sublimity** [comment]
Not an update for this bug, but just because i'm picky about organization, can you edit your comment and format the #<number> 's into the following so they don't reference other issues.

![image](https://user-images.githubusercontent.com/6015313/50562761-de9f3a80-0d51-11e9-91c8-ef31848eb2f6.png)

**Comment by Swan** [comment]
This is expected behavior. It'll happen when cancelling a leaderboard fetch request abruptly occasionally.
