### ISSUE TITLE
my pc randomly blue screens when i play a map?

### ISSUE THREAD

**Issue by texzlol** [Quaver/Quaver#4196]
### Describe the bug

it first started with the game randomly freezing, then crashing, and now it bluescreens my pc.

### To Reproduce

idk if it just happens to me, it usually bluescreens before a spam of notes appear

### Log Files

[5:46:44] - RUNTIME - DEBUG: OS: Microsoft Windows 10.0.22631
[5:46:46] - RUNTIME - IMPORTANT: Config file has been successfully read.
[5:46:46] - RUNTIME - IMPORTANT: Started IPC server on port: 43596
[5:46:47] - RUNTIME - IMPORTANT: Successfully initialized and logged into Steam as : TexZ <76561199167172671>
[5:46:47] - RUNTIME - IMPORTANT: Found 0 subscribed workshop items | # of subscribed: 14 | Entries: 1
[5:46:48] - RUNTIME - IMPORTANT: Scheduled Screen Change
[5:46:48] - RUNTIME - IMPORTANT: Screen has been switched to type: `Initialization`
[5:46:48] - RUNTIME - IMPORTANT: Loading skin...
[5:46:51] - RUNTIME - IMPORTANT: Loading fonts...
[5:46:52] - RUNTIME - IMPORTANT: Performing game initialization task... 
[5:46:52] - RUNTIME - IMPORTANT: Scores table has been created
[5:46:52] - RUNTIME - IMPORTANT: Map Database has been created
[5:46:52] - RUNTIME - IMPORTANT: Found 255 .qua files inside the song directory
[5:46:52] - RUNTIME - IMPORTANT: Playlist Table has been created
[5:46:52] - RUNTIME - IMPORTANT: PlaylistMap table has been created
[5:46:52] - RUNTIME - IMPORTANT: QuaverSettings table has been created
[5:46:52] - RUNTIME - IMPORTANT: Found 0 maps that have outdated difficulty ratings. Scheduling recalculation upon enteringselect.
[5:46:52] - RUNTIME - IMPORTANT: JudgementWindows table has been created
[5:46:52] - RUNTIME - IMPORTANT: Created preset judgement windows `Standard*` - Marv: 18 | Perf: 43 | Great: 76 | Good: 106 | Okay: 127 | Miss: 164
[5:46:52] - RUNTIME - IMPORTANT: Created preset judgement windows `Peaceful` - Marv: 23 | Perf: 57 | Great: 101 | Good: 141 | Okay: 169 | Miss: 218
[5:46:52] - RUNTIME - IMPORTANT: Created preset judgement windows `Lenient` - Marv: 21 | Perf: 52 | Great: 91 | Good: 128 | Okay: 153 | Miss: 198
[5:46:52] - RUNTIME - IMPORTANT: Created preset judgement windows `Chill` - Marv: 19 | Perf: 47 | Great: 83 | Good: 116 | Okay: 139 | Miss: 180
[5:46:52] - RUNTIME - IMPORTANT: Created preset judgement windows `Strict` - Marv: 16 | Perf: 39 | Great: 69 | Good: 96 | Okay: 127 | Miss: 164
[5:46:52] - RUNTIME - IMPORTANT: Created preset judgement windows `Tough` - Marv: 14 | Perf: 35 | Great: 62 | Good: 87 | Okay: 127 | Miss: 164
[5:46:52] - RUNTIME - IMPORTANT: Created preset judgement windows `Extreme` - Marv: 13 | Perf: 32 | Great: 57 | Good: 79 | Okay: 127 | Miss: 164
[5:46:52] - RUNTIME - IMPORTANT: Created preset judgement windows `Impossible` - Marv: 8 | Perf: 20 | Great: 35 | Good: 49 | Okay: 127 | Miss: 164
[5:46:52] - RUNTIME - IMPORTANT: UserProfile table has been created
[5:46:52] - RUNTIME - IMPORTANT: BlockedUsers table has been created
[5:46:53] - RUNTIME - IMPORTANT: Game initialization task complete!
[5:46:53] - RUNTIME - IMPORTANT: Scheduled Screen Change
[5:46:53] - RUNTIME - IMPORTANT: Removing old map backups...
[5:46:53] - RUNTIME - IMPORTANT: Removed 0 map backup(s) while keeping 0.
[5:46:54] - RUNTIME - IMPORTANT: Screen `Menu` has been loaded proceeding to switch.
[5:46:54] - RUNTIME - IMPORTANT: Screen has been switched to type: `Menu`
[5:46:57] - RUNTIME - ERROR: System.Net.WebException: The SSL connection could not be established, see inner exception.
 ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
 ---> System.Net.Sockets.SocketException (10054): An existing connection was forcibly closed by the remote host.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Security.SslStream.<FillHandshakeBufferAsync>g__InternalFillHandshakeBufferAsync|189_0[TIOAdapter](TIOAdapter adap, ValueTask`1 task, Int32 minSize)
   at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellation(CancellationToken cancellationToken)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageHandlerStage.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageHandlerStage.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.SocketsHttpHandler.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageInvoker.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.Send(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at System.Net.HttpWebRequest.SendRequest(Boolean async)
   at System.Net.HttpWebRequest.GetResponse()
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetResponse()
   at System.Net.WebClient.GetWebResponse(WebRequest request)
   at System.Net.WebClient.DownloadBits(WebRequest request, Stream writeStream)
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at System.Net.WebClient.DownloadData(String address)
   at Quaver.Shared.Online.API.News.APIRequestNewsFeed.LoadBanner(APIResponseNewsFeed feed) in D:\QuaverDeploy\Quaver\Quaver.Shared\Online\API\News\APIRequestNewsPost.cs:line 57
[5:46:59] - RUNTIME - IMPORTANT: Cleared previously available chat channels
[5:46:59] - RUNTIME - IMPORTANT: Received Twitch Connection Status: Connected: False | Username: 
[5:46:59] - RUNTIME - IMPORTANT: Received available chat channel: #first-places
[5:46:59] - RUNTIME - IMPORTANT: Joined chat channel: #first-places | Players who achieve first place on a map are shown here
[5:46:59] - RUNTIME - IMPORTANT: Received available chat channel: #quaver
[5:46:59] - RUNTIME - IMPORTANT: Joined chat channel: #quaver | General discussion about Quaver
[5:46:59] - RUNTIME - IMPORTANT: Received friends list containing 0 users.
[5:47:16] - RUNTIME - IMPORTANT: Fetching message history for channel: #quaver
[5:47:16] - RUNTIME - IMPORTANT: Finished Fetching message history for channel: #quaver w/ 20 messages!
[5:47:16] - RUNTIME - IMPORTANT: Flushed 20 messages from the `#quaver` message history queue.
[5:48:43] - RUNTIME - IMPORTANT: Discord RPC has shutdown

**Comment by AiAe** [comment]
Unsure about your bluescreen, but the logs say you have issue connecting to the servers, which indicate you probably try to use some kind of VPN which does not play nicely with SSL.
