### ISSUE TITLE
game blackscreened after opening a map

### ISSUE THREAD

**Issue by ARGEBE** [Quaver/Quaver#4349]
### Describe the bug

After opening this [map](https://quavergame.com/mapset/map/154036) I was perpetually loading in a black screen

### To Reproduce

Not consistently reproducible 

### Log Files

this error was printed, rest of log was normal
[8:14:35] - RUNTIME - ERROR: System.NullReferenceException: Object reference not set to an instance of an object.
   at Quaver.Shared.Screens.Gameplay.GameplayScreen.UpdateNextSoundEffectIndex()
   at Quaver.Shared.Screens.Gameplay.GameplayScreen..ctor(Qua map, String md5, List`1 scores, Replay replay, Boolean isPlayTesting, Double playTestTime, Boolean isCalibratingOffset, SpectatorClient spectatorClient, TournamentPlayerOptions options, Boolean isSongSelectPreview, Boolean isTestPlayingInNewEditor, Boolean useExistingAudioTime)
   at Quaver.Shared.Screens.Loading.MapLoadingScreen.<>c__DisplayClass21_0.<LoadGameplayScreen>b__0()
   at Quaver.Shared.Screens.QuaverScreenManager.LoadScreen(Func`1 newScreen, CancellationToken token)
   at Wobble.Scheduling.TaskHandler`2.<>c__DisplayClass27_0.<<Run>b__0>d.MoveNext()

**Comment by ESV-Sweetplum** [comment]
send qua

**Comment by ESV-Sweetplum** [comment]
i give up i've entered and exited the map like 20 times

**Comment by AiAe** [comment]
Cannot replicate in latest version, it might also be fixed due to how many editor fixes that we did.
Will close for now.
