### ISSUE TITLE
Renaming "Default Layer" with Shortcut crashes game

### ISSUE THREAD

**Issue by txbi** [Quaver/Quaver#4354]
### Describe the bug

While in Editor on the "Default Layer", pressing Shift+R to rename the current layer game crashes the game.

### To Reproduce

1. Open Quaver
2. Go to Singleplayer
3. Find a map of choice
4. Press right click on the map
5. Press the "Edit" button from the dropdown menu
6. Go onto the "Default Layer" in the Layers tab
7. Now, while in the Editor, press Shift+R 
8. Congratulations! You have successfully crashed your game.

### Expected behavior

Prompt a warning message that the default layer cannot be edited. This popup normally appears when you try to rename the default layer manually via the small pencil icon.
![grafik](https://github.com/user-attachments/assets/3d3321c9-1a62-49a1-99f4-d9d656eceb5b)

### Log Files

```
[1:37:24] - RUNTIME - ERROR: System.NullReferenceException: Object reference not set to an instance of an object.
   at Quaver.Shared.Screens.Edit.UI.Panels.Layers.Dialogs.DialogRenameLayer.CreateTextbox()
   at Quaver.Shared.Screens.Edit.UI.Panels.Layers.Dialogs.DialogRenameLayer..ctor(EditorLayerInfo layer, EditorActionManager manager, Qua workingMap)
   at Quaver.Shared.Screens.Edit.EditScreen.RenameLayer()
   at Quaver.Shared.Screens.Edit.Input.EditorInputManager.HandleAction(KeybindActions action, Boolean isKeyPress, Boolean isRelease)
   at Quaver.Shared.Screens.Edit.Input.EditorInputManager.HandleKeyPresses()
   at Quaver.Shared.Screens.Edit.Input.EditorInputManager.HandleInput()
   at Quaver.Shared.Screens.Edit.EditScreen.Update(GameTime gameTime)
   at Wobble.Screens.ScreenManager.Update(GameTime gameTime)
   at Wobble.WobbleGame.Update(GameTime gameTime)
   at Quaver.Shared.QuaverGame.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Microsoft.Xna.Framework.Game.Run()
   at Quaver.Program.Run()
   at Quaver.Program.Main(String[] args)
```

### Screenshots

https://github.com/user-attachments/assets/bc76bb8a-cb2a-45cb-8eed-78dfdbb3805d

:(

**Comment by txbi** [comment]
Originally found by **jack_932**
[https://discord.com/channels/743595537655136329/743595538225692746/1309257677850804318](url)
