### ISSUE TITLE
Hit Bubble NullRef Error

### ISSUE THREAD

**Issue by WilliamQiufeng** [Quaver/Quaver#4396]
### Describe the bug

Need to prevent this
```
ERROR: System.NullReferenceException: Object reference not set to an instance of an object.
   at Quaver.Shared.Screens.Gameplay.UI.Bubble.HitBubbles.get_SkinKeys()
   at Quaver.Shared.Screens.Gameplay.UI.Bubble.HitBubbles.get_HideHitBubbles()
   at Quaver.Shared.Screens.Gameplay.UI.Bubble.HitBubbles.OnRectangleRecalculated()
   at Wobble.Graphics.Drawable.RecalculateRectangles()
   at Wobble.Graphics.Drawable.set_Parent(Drawable value)
   at Wobble.Graphics.Drawable.set_Parent(Drawable value)
   at Wobble.Graphics.Drawable.set_Parent(Drawable value)
   at Quaver.Shared.Screens.Selection.UI.Preview.SelectMapPreviewContainer.OnMapChanged(Object sender, BindableValueChangedEventArgs`1 e)
   at Quaver.Shared.Screens.Multi.MultiplayerGameScreen.SelectMultiplayerMap()
   at Quaver.Shared.Screens.Multi.MultiplayerGameScreen..ctor()
   at Quaver.Shared.Online.OnlineManager.<>c.<OnJoinedMultiplayerGame>b__78_1()
   at Quaver.Shared.Screens.QuaverScreenManager.LoadScreen(Func`1 newScreen, CancellationToken token)
   at Wobble.Scheduling.TaskHandler`2.<>c__DisplayClass27_0.<<Run>b__0>d.MoveNext()
```

### To Reproduce

n/a

### Log Files

^

**Comment by ESV-Sweetplum** [comment]
noted that this bug only occurs upon joining a lobby with an invite; password works fine.
