### ISSUE TITLE
Game doesn't launch at all

### ISSUE THREAD

**Issue by Kasumiikun** [Quaver/Quaver#590]
**Describe the bug**
Basically, the game doesn't launch at all when I launch it via Steam. No black screen or anything, It just stays the same as before I launched Quaver. The game does not show up as a background process either.

**Expected behavior**
Quaver actually launching.

**Screenshots**
Here is a GIF showing what happens. https://htfarmingiscool.s-ul.eu/8zOzWObD
 
**Desktop (please complete the following information):**
 - OS: Windows 10
 - Processor: Intel Core 2 Duo CPU 3Ghz
 - 4Go RAM

**Additional context**
Here is the runtime.log of this happening. "[6:49:34] - RUNTIME - IMPORTANT: Config file has been successfully read.
[6:49:34] - RUNTIME - IMPORTANT: Successfully initialized and logged into Steam as : Kasumi <76561198188478834>
[6:49:35] - RUNTIME - ERROR: Microsoft.Xna.Framework.Graphics.NoSuitableGraphicsDeviceException: Failed to create graphics device! ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.FramebufferHelper.BindFramebuffer(Int32 framebuffer)
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.PlatformApplyDefaultRenderTarget()
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.ApplyRenderTargets(RenderTargetBinding[] renderTargets)
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.Initialize()
   at Microsoft.Xna.Framework.GraphicsDeviceManager.CreateDevice(GraphicsDeviceInformation gdi)
   at Microsoft.Xna.Framework.GraphicsDeviceManager.CreateDevice()
   --- End of inner exception stack trace ---
   at Microsoft.Xna.Framework.GraphicsDeviceManager.CreateDevice()
   at Microsoft.Xna.Framework.GraphicsDeviceManager.ApplyChanges()
   at Quaver.Program.Main()"

**Comment by Swan** [comment]
Try updating your graphics drivers, and make sure that your gpu meets the minimum requirements as listed on the [Steam store page](https://store.steampowered.com/app/980610/Quaver/)
