### ISSUE TITLE
Uploading failed reading JObject

### ISSUE THREAD

**Issue by AiAe** [Quaver/Quaver#632]
`[3:29:47] - NETWORK - ERROR: Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Path '', line 0, position 0.
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at Quaver.Server.Client.OnlineClient.UploadMapset(String file)
   at Quaver.Shared.Screens.Editor.UI.Dialogs.EditorUploadMapsetDialog.<UploadMapset>b__45_0()
`

Map: https://www.dropbox.com/s/69qiceytnfgvg22/The%20Bangles%20-%20Walk%20Like%20an%20Egyptian%20-%20321020.qp?dl=0

**Comment by arzenvald** [comment]
https://quavergame.com/mapsets/349 
[network.log](https://github.com/Quaver/Quaver/files/3346048/network.log)
