### ISSUE TITLE
Game Crashes w/ Full LN 

### ISSUE THREAD

**Issue by Swan** [Quaver/Quaver#721]
If you create a map with only one note in the beginning and turn on Full LN, it'll crash the game.

```
[10:57:58] - RUNTIME - ERROR: System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Quaver.API.Maps.Qua.GetCommonBpm() in C:\Users\admin\Desktop\Git\Quaver\Quaver.API\Quaver.API\Maps\Qua.cs:line 338
   at Quaver.Shared.Screens.Gameplay.Rulesets.Keys.HitObjects.HitObjectManagerKeys.InitializeScrollVelocities(Qua qua) in C:\Users\admin\Desktop\Git\Quaver\Quaver.Shared\Screens\Gameplay\Rulesets\Keys\HitObjects\HitObjectManagerKeys.cs:line 535
   at Quaver.Shared.Screens.Gameplay.Rulesets.Keys.HitObjects.HitObjectManagerKeys..ctor(GameplayRulesetKeys ruleset, Qua map) in C:\Users\admin\Desktop\Git\Quaver\Quaver.Shared\Screens\Gameplay\Rulesets\Keys\HitObjects\HitObjectManagerKeys.cs:line 217
   at Quaver.Shared.Screens.Gameplay.Rulesets.Keys.GameplayRulesetKeys.CreateHitObjectManager() in C:\Users\admin\Desktop\Git\Quaver\Quaver.Shared\Screens\Gameplay\Rulesets\Keys\GameplayRulesetKeys.cs:line 123
   at Quaver.Shared.Screens.Gameplay.Rulesets.GameplayRuleset..ctor(GameplayScreen screen, Qua map) in C:\Users\admin\Desktop\Git\Quaver\Quaver.Shared\Screens\Gameplay\Rulesets\GameplayRuleset.cs:line 65
   at Quaver.Shared.Screens.Gameplay.Rulesets.Keys.GameplayRulesetKeys..ctor(GameplayScreen screen, Qua map) in C:\Users\admin\Desktop\Git\Quaver\Quaver.Shared\Screens\Gameplay\Rulesets\Keys\GameplayRulesetKeys.cs:line 66
   at Quaver.Shared.Screens.Gameplay.GameplayScreen.SetRuleset() in C:\Users\admin\Desktop\Git\Quaver\Quaver.Shared\Screens\Gameplay\GameplayScreen.cs:line 519
   at Quaver.Shared.Screens.Gameplay.GameplayScreen..ctor(Qua map, String md5, List`1 scores, Replay replay, Boolean isPlayTesting, Double playTestTime, Boolean isCalibratingOffset) in C:\Users\admin\Desktop\Git\Quaver\Quaver.Shared\Screens\Gameplay\GameplayScr
een.cs:line 318
   at Quaver.Shared.Screens.Loading.MapLoadingScreen.<>c__DisplayClass18_0.<LoadGameplayScreen>b__0() in C:\Users\admin\Desktop\Git\Quaver\Quaver.Shared\Screens\Loading\MapLoadingScreen.cs:line 195
   at Quaver.Shared.Screens.QuaverScreenManager.<>c__DisplayClass24_0.<ScheduleScreenChange>b__0() in C:\Users\admin\Desktop\Git\Quaver\Quaver.Shared\Screens\QuaverScreenManager.cs:line 203
   at Quaver.Shared.Scheduling.ThreadScheduler.<>c__DisplayClass1_0.<Run>b__0() in C:\Users\admin\Desktop\Git\Quaver\Quaver.Shared\Scheduling\ThreadScheduler.cs:line 38
```

**Comment by YaLTeR** [comment]
Alright, so the issue here is that Full LN removes the single note resulting in zero hit objects, which is an invalid (it's even checked against in `IsValid()`). I will adjust Full LN to not remove single notes like this.
