### ISSUE TITLE
Doesn't launch on Linux Mint

### ISSUE THREAD

**Issue by YaLTeR** [Quaver/Quaver#804]
```
[3:20:09] - RUNTIME - DEBUG: OS: Linux 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018
[3:20:09] - RUNTIME - ERROR: System.TypeInitializationException: The type initializer for 'Gdip' threw an exception. ---> System.DllNotFoundException: Unable to load shared library 'libdl' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibdl: cannot open shared object file: No such file or directory
   at Interop.Libdl.dlopen(String fileName, Int32 flag)
   at System.Drawing.SafeNativeMethods.Gdip.LoadNativeLibrary()
   at System.Drawing.SafeNativeMethods.Gdip..cctor()
   --- End of inner exception stack trace ---
   at System.Drawing.SafeNativeMethods.Gdip.GdipNewPrivateFontCollection(IntPtr& fontCollection)
   at Wobble.Graphics.BitmapFonts.BitmapFontFactory.AddFont(String name, Byte[] fontBytes)
   at Quaver.Shared.Assets.Fonts.Load()
   at Quaver.Shared.QuaverGame.LoadContent()
   at Quaver.Shared.QuaverGame.Initialize()
   at Microsoft.Xna.Framework.Game.DoInitialize()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Quaver.Program.Main()
```

**Comment by YaLTeR** [comment]
Can be fixed by `sudo apt install libgdiplus libc6-dev`.
