### ISSUE TITLE
Editor crashed upon pressing Escape, Unable to relaunch

### ISSUE THREAD

**Issue by imlights** [Quaver/Quaver#900]
**Describe the bug**
I was editing a map, attempted to copy some notes, and Quaver exited with the following crash log:

[1:16:50] - RUNTIME - ERROR: System.DllNotFoundException: Unable to load shared library 'User32.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libUser32.dll: cannot open shared object file: No such file or directory
   at Wobble.Platform.Windows.WindowsClipboard.OpenClipboard(IntPtr hWndNewOwner)
   at Wobble.Platform.Windows.WindowsClipboard.SetText(String selectedText)
   at Quaver.Shared.Screens.Editor.UI.Rulesets.Keys.EditorRulesetKeys.CopySelectedHitObjects()
   at Quaver.Shared.Screens.Editor.UI.EditorMenuBar.CreateEditSection()
   at Quaver.Shared.Screens.Editor.UI.EditorMenuBar.RenderImguiLayout()
   at Wobble.Graphics.ImGUI.SpriteImGui.Draw(GameTime gameTime)
   at Quaver.Shared.Screens.Editor.EditorScreenView.Draw(GameTime gameTime)
   at Quaver.Shared.QuaverGame.Draw(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Quaver.Program.Main()
[1:16:50] - RUNTIME - IMPORTANT: Detected game crash. Autosaving map

Upon attempting to relaunch via steam and manually, the following error was thrown:

[1:19:02] - RUNTIME - ERROR: SQLite.SQLiteException: database is locked
   at SQLite.SQLite3.Prepare2(sqlite3 db, String query)
   at SQLite.SQLiteCommand.Prepare()
   at SQLite.SQLiteCommand.ExecuteScalar[T]()
   at SQLite.SQLiteConnection.ExecuteScalar[T](String query, Object[] args)
   at SQLite.SQLiteConnection..ctor(String databasePath, SQLiteOpenFlags openFlags, Boolean storeDateTimeAsTicks, Object key)
   at Quaver.Shared.Database.Maps.MapDatabaseCache.FetchAll()
   at Quaver.Shared.Database.Maps.MapDatabaseCache.OrderAndSetMapsets()
   at Quaver.Shared.Database.Maps.MapDatabaseCache.Load(Boolean fullSync)
   at Quaver.Shared.QuaverGame.PerformGameSetup()
   at Quaver.Shared.QuaverGame.Initialize()
   at Microsoft.Xna.Framework.Game.DoInitialize()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Quaver.Program.Main()

**Desktop (please complete the following information):**
 - OS: Manjaro Linux

**Additional context**
Not the first time i've launched the editor and messed around, but the first time i've had any problems.

**Comment by YaLTeR** [comment]
Ah that's because @Swan hardcoded the windows clipboard:
https://github.com/Quaver/Quaver/blob/ef23eedace5b090f7f5a74fd11fb7b08558389d4/Quaver.Shared/Screens/Editor/UI/Rulesets/Keys/EditorRulesetKeys.cs#L699
