### ISSUE TITLE
Game doesn't start if it can't open alsa and it doesn't try pulseaudio

### ISSUE THREAD

**Issue by rainyuu** [Quaver/Quaver#933]
**issue:**
game gives up after trying to open alsa and not being able to, never tries pulseaudio (at least that's what i could read from the logs, could be wrong)

**steps:**
1. install gentoo
2. open the game after unzipping it into a folder from the latest tag and `chmod +x quaver.sh` then `dos2unix quaver.sh` 
3. doesnt work does it now

**expected behavior:**
the game actually wokring

**machine:**
 - OS: Gentoo Linux on Linux 5.1.2-zen1-tooru-best-girl
 - dotnet: dotnetcore-sdk-bin ver 2.2.105
 - pulseaudio: version 12.2-r1, USE flags: X alsa alsa-plugin asyncns caps gdbm glib gtk ipv6 orc ssl systemd tcpd udev webrtc-aec -bluetooth -dbus -doc -elogind -equalizer -gconf -jack -libressl -libsamplerate -lirc -native-headset -neon -ofono-headset -oss -qt5 -realtime -selinux -sox -system-wide -test -zeroconf 
 - game version: latest tag

**log:**
```~/p/quaver2 > ./quaver.sh
[11:56:32] - RUNTIME - IMPORTANT: Config file has been successfully read.
Setting breakpad minidump AppID = 480
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198219460008 [API loaded no]
[11:56:32] - RUNTIME - IMPORTANT: Successfully initialized and logged into Steam as : lily <76561198219460008>
[11:56:33] - RUNTIME - IMPORTANT: Config file has been successfully read.
[11:56:33] - RUNTIME - IMPORTANT: Scores table has been created
[11:56:33] - RUNTIME - IMPORTANT: Map Database has been created
[11:56:33] - RUNTIME - IMPORTANT: Found 7 .qua files inside the song directory
[11:56:37] - RUNTIME - IMPORTANT: QuaverSettings table has been created
[11:56:37] - RUNTIME - IMPORTANT: QuaverSettings could not be found previously in the database.
[11:56:37] - RUNTIME - IMPORTANT: Found 0 maps that have outdated difficulty ratings. Scheduling recalculation upon enteringselect.
[11:56:37] - RUNTIME - DEBUG: OS: Linux 5.1.2-zen1-tooru-best-girl \#1 ZEN SMP Wed May 15 22:14:12 CEST 2019
[11:56:37] - NETWORK - DEBUG: OS: Linux 5.1.2-zen1-tooru-best-girl \#1 ZEN SMP Wed May 15 22:14:12 CEST 2019
[11:56:37] - RUNTIME - DEBUG: BASS options: DevicePeriod = 10, DeviceBufferLength = 40
ALSA lib /var/tmp/portage/media-libs/alsa-lib-1.1.9/work/alsa-lib-1.1.9/src/pcm/pcm_dmix.c:1108:(snd_pcm_dmix_open) unable to open slave
[11:56:37] - RUNTIME - ERROR: Wobble.Audio.AudioEngineException: BASS has failed to initialize (error code: 46, name: "Busy")! Are your platform-specific dlls present?
   at Wobble.Audio.AudioManager.Initialize(Nullable\`1 devicePeriod, Nullable\`1 deviceBufferLength) in C:\Users\swan\Desktop\git\Quaver\Wobble\Wobble\Audio\AudioManager.cs:line 51
   at Wobble.WobbleGame.Initialize() in C:\Users\swan\Desktop\git\Quaver\Wobble\Wobble\WobbleGame.cs:line 123
   at Quaver.Shared.QuaverGame.Initialize() in C:\Users\swan\Desktop\git\Quaver\Quaver.Shared\QuaverGame.cs:line 141
   at Microsoft.Xna.Framework.Game.DoInitialize() in C:\Users\swan\Desktop\git\Quaver\Wobble\MonoGame\MonoGame.Framework\Game.cs:line 681
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in C:\Users\swan\Desktop\git\Quaver\Wobble\MonoGame\MonoGame.Framework\Game.cs:line 384
   at Quaver.Program.Main() in C:\Users\swan\Desktop\git\Quaver\Quaver\Program.cs:line 60

Unhandled Exception: Wobble.Audio.AudioEngineException: BASS has failed to initialize (error code: 46, name: "Busy")! Are your platform-specific dlls present?
   at Wobble.Audio.AudioManager.Initialize(Nullable\`1 devicePeriod, Nullable\`1 deviceBufferLength) in C:\Users\swan\Desktop\git\Quaver\Wobble\Wobble\Audio\AudioManager.cs:line 51
   at Wobble.WobbleGame.Initialize() in C:\Users\swan\Desktop\git\Quaver\Wobble\Wobble\WobbleGame.cs:line 123
   at Quaver.Shared.QuaverGame.Initialize() in C:\Users\swan\Desktop\git\Quaver\Quaver.Shared\QuaverGame.cs:line 141
   at Microsoft.Xna.Framework.Game.DoInitialize() in C:\Users\swan\Desktop\git\Quaver\Wobble\MonoGame\MonoGame.Framework\Game.cs:line 681
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in C:\Users\swan\Desktop\git\Quaver\Wobble\MonoGame\MonoGame.Framework\Game.cs:line 384
   at Quaver.Program.Main() in C:\Users\swan\Desktop\git\Quaver\Quaver\Program.cs:line 60
fish: “./quaver.sh” terminated by signal SIGABRT (Abort)```

**Comment by YaLTeR** [comment]
So from what I know, BASS only has an ALSA backend and not a PA backend. On a typical PA setup there's an ALSA config that forwards all ALSA clients to PA (for example, on Arch it's provided by the [pulseaudio-alsa](https://www.archlinux.org/packages/extra/any/pulseaudio-alsa/) package). My guess would be that you don't have this set up or something, so check it. Otherwise I'm not sure.

**Comment by rainyuu** [comment]
and once again you have solved my issue, thanks for that.
