### ISSUE TITLE
game crash when a screenshot is taken

### ISSUE THREAD

**Issue by zabaplays** [Quaver/Quaver#950]
anytime i take a screenshot the game crashes followed by the "quaver has stopped working" message.

**Comment by YaLTeR** [comment]
How do you take the screenshot? Do you use any screenshot programs? Could you send `Logs/runtime.log`?

**Comment by zabaplays** [comment]
> How do you take the screenshot? Do you use any screenshot programs? Could you send `Logs/runtime.log`?

i use the steam screenshot function by pressing f12

heres the log:
`[12:09:27] - RUNTIME - DEBUG: OS: Microsoft Windows 6.1.7601 S
[12:09:28] - RUNTIME - IMPORTANT: Config file has been successfully read.
[12:09:28] - RUNTIME - IMPORTANT: Successfully initialized and logged into Steam as : Voxargenteae <76561198143023646>
[12:09:31] - RUNTIME - IMPORTANT: Config file has been successfully read.
[12:09:32] - RUNTIME - IMPORTANT: Scores table has been created
[12:09:32] - RUNTIME - IMPORTANT: Map Database has been created
[12:09:32] - RUNTIME - IMPORTANT: Found 436 .qua files inside the song directory
[12:09:50] - RUNTIME - IMPORTANT: OtherGameMaps table has been created.
[12:09:51] - RUNTIME - IMPORTANT: Starting sync of other game maps...
[12:09:51] - RUNTIME - ERROR: System.ArgumentException: Empty path name is not legal.
Parameter name: path
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at osu_database_reader.BinaryFiles.OsuDb.Read(String path)
   at Quaver.Shared.Database.Maps.OtherGameMapDatabaseCache.LoadOsuBeatmapDatabase()
[12:09:51] - RUNTIME - IMPORTANT: QuaverSettings table has been created
[12:09:52] - RUNTIME - IMPORTANT: Found 0 maps that have outdated difficulty ratings. Scheduling recalculation upon enteringselect.
[12:09:52] - RUNTIME - DEBUG: BASS options: DevicePeriod = -1, DeviceBufferLength = 10
[12:09:52] - RUNTIME - DEBUG: BASS version: 2.4.13.8
[12:10:06] - RUNTIME - DEBUG: Currently running Quaver version: `0.15.4`
[12:10:10] - RUNTIME - IMPORTANT: Scheduled screen change to: 'Menu'. w/ 0ms delay
[12:10:13] - RUNTIME - DEBUG: Selected new jukebox track (0): Yu-dachi - Shukufuku no shikisai wa omoi musubu kimitachimade [EXHAUST] 
[12:10:18] - RUNTIME - DEBUG: There are now 1 total available users.
[12:10:19] - RUNTIME - DEBUG: There are now 14 total available users.
[12:10:25] - RUNTIME - DEBUG: There are now 15 total available users.
[12:10:36] - RUNTIME - DEBUG: There are currently: 136 available mapsets to play in select.
[12:10:38] - RUNTIME - IMPORTANT: Scheduled screen change to: 'Select'. w/ 0ms delay
[12:10:40] - RUNTIME - DEBUG: Updated map: 184379bde78ef4e61aab02a7435cc976 (#352) in the cache
[12:10:47] - RUNTIME - IMPORTANT: Scheduled screen change to: 'Loading'. w/ 100ms delay
[12:10:47] - RUNTIME - IMPORTANT: Changed to Screen 'Loading'
[12:10:50] - RUNTIME - IMPORTANT: Scheduled screen change to: 'Gameplay'. w/ 0ms delay
[12:11:00] - RUNTIME - IMPORTANT: Scheduled screen change to: 'Results'. w/ 500ms delay
[12:11:01] - RUNTIME - IMPORTANT: Changed to Screen 'Results'
[12:11:05] - RUNTIME - ERROR: Microsoft.Xna.Framework.Graphics.MonoGameGLException: GL.GetError() returned 1282
   at Microsoft.Xna.Framework.Graphics.GraphicsExtensions.CheckGLError()
   at Microsoft.Xna.Framework.Graphics.ConstantBuffer.PlatformApply(GraphicsDevice device, ShaderProgram program)
   at Microsoft.Xna.Framework.Graphics.ConstantBufferCollection.SetConstantBuffers(GraphicsDevice device, ShaderProgram shaderProgram)
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.PlatformApplyState(Boolean applyShaders)
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.PlatformDrawUserIndexedPrimitives[T](PrimitiveType primitiveType, T[] vertexData, Int32 vertexOffset, Int32 numVertices, Int16[] indexData, Int32 indexOffset, Int32 primitiveCount, VertexDeclaration vertexDeclaration)
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawUserIndexedPrimitives[T](PrimitiveType primitiveType, T[] vertexData, Int32 vertexOffset, Int32 numVertices, Int16[] indexData, Int32 indexOffset, Int32 primitiveCount, VertexDeclaration vertexDeclaration)
   at Microsoft.Xna.Framework.Graphics.SpriteBatcher.FlushVertexArray(Int32 start, Int32 end, Effect effect, Texture texture)
   at Microsoft.Xna.Framework.Graphics.SpriteBatcher.DrawBatch(SpriteSortMode sortMode, Effect effect)
   at Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(Texture2D texture, RectangleF destinationRectangle, Nullable`1 sourceRectangle, Color color, Single rotation, Vector2 origin, SpriteEffects effects, Single layerDepth)
   at Wobble.Graphics.Sprites.Sprite.DrawToSpriteBatch()
   at Wobble.Graphics.Sprites.Sprite.Draw(GameTime gameTime)
   at Wobble.Graphics.Sprites.ScrollContainer.Draw(GameTime gameTime)
   at Wobble.Graphics.Drawable.Draw(GameTime gameTime)
[12:11:05] - RUNTIME - ERROR: Microsoft.Xna.Framework.Graphics.MonoGameGLException: GL.GetError() returned 1282
   at Microsoft.Xna.Framework.Graphics.GraphicsExtensions.CheckGLError()
   at Microsoft.Xna.Framework.Graphics.ConstantBuffer.PlatformApply(GraphicsDevice device, ShaderProgram program)
   at Microsoft.Xna.Framework.Graphics.ConstantBufferCollection.SetConstantBuffers(GraphicsDevice device, ShaderProgram shaderProgram)
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.PlatformApplyState(Boolean applyShaders)
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.PlatformDrawUserIndexedPrimitives[T](PrimitiveType primitiveType, T[] vertexData, Int32 vertexOffset, Int32 numVertices, Int16[] indexData, Int32 indexOffset, Int32 primitiveCount, VertexDeclaration vertexDeclaration)
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawUserIndexedPrimitives[T](PrimitiveType primitiveType, T[] vertexData, Int32 vertexOffset, Int32 numVertices, Int16[] indexData, Int32 indexOffset, Int32 primitiveCount, VertexDeclaration vertexDeclaration)
   at Microsoft.Xna.Framework.Graphics.SpriteBatcher.FlushVertexArray(Int32 start, Int32 end, Effect effect, Texture texture)
   at Microsoft.Xna.Framework.Graphics.SpriteBatcher.DrawBatch(SpriteSortMode sortMode, Effect effect)
   at Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(Texture2D texture, RectangleF destinationRectangle, Nullable`1 sourceRectangle, Color color, Single rotation, Vector2 origin, SpriteEffects effects, Single layerDepth)
   at Wobble.Graphics.Sprites.Sprite.DrawToSpriteBatch()
   at Wobble.Graphics.Sprites.Sprite.Draw(GameTime gameTime)
   at Wobble.Graphics.Drawable.Draw(GameTime gameTime)
[12:11:05] - RUNTIME - ERROR: Microsoft.Xna.Framework.Graphics.MonoGameGLException: GL.GetError() returned 1282
   at Microsoft.Xna.Framework.Graphics.GraphicsExtensions.CheckGLError()
   at Microsoft.Xna.Framework.Graphics.ConstantBuffer.PlatformApply(GraphicsDevice device, ShaderProgram program)
   at Microsoft.Xna.Framework.Graphics.ConstantBufferCollection.SetConstantBuffers(GraphicsDevice device, ShaderProgram shaderProgram)
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.PlatformApplyState(Boolean applyShaders)
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.PlatformDrawUserIndexedPrimitives[T](PrimitiveType primitiveType, T[] vertexData, Int32 vertexOffset, Int32 numVertices, Int16[] indexData, Int32 indexOffset, Int32 primitiveCount, VertexDeclaration vertexDeclaration)
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawUserIndexedPrimitives[T](PrimitiveType primitiveType, T[] vertexData, Int32 vertexOffset, Int32 numVertices, Int16[] indexData, Int32 indexOffset, Int32 primitiveCount, VertexDeclaration vertexDeclaration)
   at Microsoft.Xna.Framework.Graphics.SpriteBatcher.FlushVertexArray(Int32 start, Int32 end, Effect effect, Texture texture)
   at Microsoft.Xna.Framework.Graphics.SpriteBatcher.DrawBatch(SpriteSortMode sortMode, Effect effect)
   at Wobble.Graphics.SpriteBatchOptions.Begin()
   at Wobble.Graphics.Sprites.Sprite.Draw(GameTime gameTime)
   at Wobble.Graphics.Drawable.Draw(GameTime gameTime)
[12:11:05] - RUNTIME - ERROR: Microsoft.Xna.Framework.Graphics.MonoGameGLException: GL.GetError() returned 1282
   at Microsoft.Xna.Framework.Graphics.GraphicsExtensions.CheckGLError()
   at Microsoft.Xna.Framework.Graphics.ConstantBuffer.PlatformApply(GraphicsDevice device, ShaderProgram program)
   at Microsoft.Xna.Framework.Graphics.ConstantBufferCollection.SetConstantBuffers(GraphicsDevice device, ShaderProgram shaderProgram)
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.PlatformApplyState(Boolean applyShaders)
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.PlatformDrawUserIndexedPrimitives[T](PrimitiveType primitiveType, T[] vertexData, Int32 vertexOffset, Int32 numVertices, Int16[] indexData, Int32 indexOffset, Int32 primitiveCount, VertexDeclaration vertexDeclaration)
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawUserIndexedPrimitives[T](PrimitiveType primitiveType, T[] vertexData, Int32 vertexOffset, Int32 numVertices, Int16[] indexData, Int32 indexOffset, Int32 primitiveCount, VertexDeclaration vertexDeclaration)
   at Microsoft.Xna.Framework.Graphics.SpriteBatcher.FlushVertexArray(Int32 start, Int32 end, Effect effect, Texture texture)
   at Microsoft.Xna.Framework.Graphics.SpriteBatcher.DrawBatch(SpriteSortMode sortMode, Effect effect)
   at Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(Texture2D texture, RectangleF destinationRectangle, Nullable`1 sourceRectangle, Color color, Single rotation, Vector2 origin, SpriteEffects effects, Single layerDepth)
   at Wobble.Graphics.Sprites.Sprite.DrawToSpriteBatch()
   at Wobble.Graphics.Sprites.Sprite.Draw(GameTime gameTime)
   at Wobble.Graphics.Drawable.Draw(GameTime gameTime)
[12:11:05] - RUNTIME - ERROR: Microsoft.Xna.Framework.Graphics.MonoGameGLException: GL.GetError() returned 1282
   at Microsoft.Xna.Framework.Graphics.GraphicsExtensions.CheckGLError()
   at Microsoft.Xna.Framework.Graphics.ConstantBuffer.PlatformApply(GraphicsDevice device, ShaderProgram program)
   at Microsoft.Xna.Framework.Graphics.ConstantBufferCollection.SetConstantBuffers(GraphicsDevice device, ShaderProgram shaderProgram)
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.PlatformApplyState(Boolean applyShaders)
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.PlatformDrawUserIndexedPrimitives[T](PrimitiveType primitiveType, T[] vertexData, Int32 vertexOffset, Int32 numVertices, Int16[] indexData, Int32 indexOffset, Int32 primitiveCount, VertexDeclaration vertexDeclaration)
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawUserIndexedPrimitives[T](PrimitiveType primitiveType, T[] vertexData, Int32 vertexOffset, Int32 numVertices, Int16[] indexData, Int32 indexOffset, Int32 primitiveCount, VertexDeclaration vertexDeclaration)
   at Microsoft.Xna.Framework.Graphics.SpriteBatcher.FlushVertexArray(Int32 start, Int32 end, Effect effect, Texture texture)
   at Microsoft.Xna.Framework.Graphics.SpriteBatcher.DrawBatch(SpriteSortMode sortMode, Effect effect)
   at Wobble.Graphics.SpriteBatchOptions.Begin()
   at Wobble.Graphics.Sprites.Sprite.Draw(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Quaver.Program.Main()
`
