### ISSUE TITLE
game not launching on linux

### ISSUE THREAD

**Issue by zabaplays** [Quaver/Quaver#956]
game not opening when launched from steam. i have done the command in the linux FAQ and rebooted. OS is pop!_OS 19.04
runtime log:
[10:01:37] - RUNTIME - DEBUG: OS: Linux 5.0.0-21-generic #22~system76-Ubuntu SMP Fri Jul 5 18:10:39 UTC 2019
[10:01:37] - RUNTIME - IMPORTANT: Config file has been successfully read.
[10:01:37] - RUNTIME - IMPORTANT: Successfully initialized and logged into Steam as : Voxargenteae <76561198143023646>
[10:01:38] - RUNTIME - IMPORTANT: Config file has been successfully read.
[10:01:38] - RUNTIME - IMPORTANT: Scores table has been created
[10:01:38] - RUNTIME - IMPORTANT: Map Database has been created
[10:01:38] - RUNTIME - IMPORTANT: Found 0 .qua files inside the song directory
[10:01:38] - RUNTIME - IMPORTANT: QuaverSettings table has been created
[10:01:38] - RUNTIME - IMPORTANT: Found 0 maps that have outdated difficulty ratings. Scheduling recalculation upon enteringselect.
[10:01:38] - RUNTIME - DEBUG: BASS options: DevicePeriod = 10, DeviceBufferLength = 40
[10:01:38] - RUNTIME - ERROR: Wobble.Audio.AudioEngineException: BASS has failed to initialize (error code: 3, name: "Driver")! Are your platform-specific dlls present?
   at Wobble.Audio.AudioManager.Initialize(Nullable`1 devicePeriod, Nullable`1 deviceBufferLength)
   at Wobble.WobbleGame.Initialize()
   at Quaver.Shared.QuaverGame.Initialize()
   at Microsoft.Xna.Framework.Game.DoInitialize()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Quaver.Program.Main()

**Comment by Sublimity** [comment]
Try installing `libbass` via your distro's package manager.

**Comment by xslendix** [comment]
I have the same problem, I have both libbass and pulseaudio-alsa installed, and I get this in the runtime logs:
```[10:06:51] - RUNTIME - DEBUG: OS: Linux 5.7.10-artix1-1 #1 SMP PREEMPT Thu, 23 Jul 2020 15:41:52 +0000
[10:06:52] - RUNTIME - IMPORTANT: Config file has been successfully read.
[10:06:52] - RUNTIME - IMPORTANT: Started IPC server on port: 43596
[10:06:52] - RUNTIME - IMPORTANT: Successfully initialized and logged into Steam as : xSlendiX <76561198213388807>
[10:06:52] - RUNTIME - IMPORTANT: Found 0 subscribed workshop items | # of subscribed: 4 | Entries: 1
[10:06:52] - RUNTIME - DEBUG: BASS options: DevicePeriod = 2, DeviceBufferLength = 8
[10:06:52] - RUNTIME - ERROR: Wobble.Audio.AudioEngineException: BASS has failed to initialize (error code: 3, name: "Driver")! Are your platform-specific dlls present?
   at Wobble.Audio.AudioManager.Initialize(Nullable`1 devicePeriod, Nullable`1 deviceBufferLength)
   at Wobble.WobbleGame.Initialize()
   at Quaver.Shared.QuaverGame.Initialize()
   at Microsoft.Xna.Framework.Game.DoInitialize()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Microsoft.Xna.Framework.Game.Run()
   at Quaver.Program.Run()
   at Quaver.Program.Main(String[] args)
```

**Comment by YaLTeR** [comment]
Please check that:
- your pulseaudio-alsa is working correctly (try some other ALSA program, like aplay, although that's not a perfect indicator)
- you don't have weird `~/.asoundrc` or similar
