### ISSUE TITLE
game immediately crashes

### ISSUE THREAD

**Issue by zabaplays** [Quaver/Quaver#968]
**Describe the bug**
when i open the game instantly crashes to the "quaver has stopped working" message

**To Reproduce**
1. open the game

**Expected behavior**
the game launches

**Desktop (please complete the following information):**
 - OS: windows 7

**Additional context**
runtime.log:
[2:55:16] - RUNTIME - DEBUG: OS: Microsoft Windows 6.1.7601 S
[2:55:17] - RUNTIME - IMPORTANT: Config file has been successfully read.
[2:55:17] - RUNTIME - IMPORTANT: Successfully initialized and logged into Steam as : Voxargenteae <76561198143023646>
[2:55:18] - RUNTIME - ERROR: Microsoft.Xna.Framework.Graphics.NoSuitableGraphicsDeviceException: Failed to create graphics device! ---> Microsoft.Xna.Framework.Graphics.MonoGameGLException: GL.GetError() returned 1280
   at Microsoft.Xna.Framework.Graphics.GraphicsExtensions.CheckGLError()
   at Microsoft.Xna.Framework.Graphics.BlendState.PlatformApplyState(GraphicsDevice device, Boolean force)
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.PlatformInitialize()
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.Initialize()
   at Microsoft.Xna.Framework.GraphicsDeviceManager.CreateDevice(GraphicsDeviceInformation gdi)
   at Microsoft.Xna.Framework.GraphicsDeviceManager.CreateDevice()
   --- End of inner exception stack trace ---
   at Microsoft.Xna.Framework.GraphicsDeviceManager.CreateDevice()
   at Microsoft.Xna.Framework.GraphicsDeviceManager.ApplyChanges()
   at Quaver.Program.Main()

**Comment by Sublimity** [comment]
Your graphics device isn't compatible, this could either be the result of the devices drivers being out of date or not even installed, or the device your computer uses is integrated graphics.
